"""Filesystem lifecycle of MANIAC-managed manpath entries (ADR-0028, ADR-0031, ADR-0032).

Every transition a managed page can undergo lives here: seeding pre-manifest
state, recovering legacy copies, migrating verified vendor copies to direct
provider links, materializing durable targets, replacing manpath links and
removing superseded ones.  `manifest` only serializes; nothing in this module
runs as an effect of deserializing it.
"""

import shutil
from dataclasses import replace
from pathlib import Path
from typing import Any

from . import manifest
from .config import Config
from .logging import logger
from .manifest import Entry, Tier
from .sources.manpages import find_install_root_manpages, select_primary_manpage
from .sources.pathcache import resolve_cached

PROVENANCE_SIGNATURE = r".\" Generated by MANIAC (https://github.com/susensio/maniac)"


def read_provenance_header(file_path: str | Path) -> dict[str, str] | None:
    """Read provenance metadata from the header of a roff manpage file."""
    path = Path(file_path)
    if not path.exists() or not path.is_file():
        return None

    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            first_line = f.readline().strip()
            if first_line != PROVENANCE_SIGNATURE:
                return None
            second_line = f.readline().strip()
    except PermissionError:
        # Distinguish "can't read it" from "read it, not ours" -- the caller
        # should not treat a permission failure as a foreign/vendor page.
        logger.warning("Permission denied reading manpage header", path=str(path))
        raise
    except OSError:
        return None

    metadata = {"tool": path.stem, "date": "unknown", "model": "unknown"}
    if second_line.startswith(r".\" "):
        meta_content = second_line[4:].strip()
        for item in meta_content.split("|"):
            parts = item.split(":", 1)
            if len(parts) == 2:
                key = parts[0].strip().lower()
                val = parts[1].strip()
                metadata[key] = val

    return metadata


def list_installed_manpages(
    config: Config | None = None,
) -> list[dict[str, Any]]:
    """Scan and list all MANIAC-managed manual pages with metadata.

    Used only as ADR-0017's manifest-migration seeder: whether a page has a
    backup is the manifest entry's `backup` field from here on, not
    something this scan probes for.
    """
    cfg = config or Config()
    results: list[dict[str, Any]] = []
    seen_tools: set[str] = set()

    for search_dir in (cfg.man_dir, cfg.output_dir):
        if not search_dir.exists():
            continue
        for file_path in search_dir.glob("*.1"):
            prov = read_provenance_header(file_path)
            if prov is not None:
                tool = prov.get("tool", file_path.stem)
                if tool in seen_tools:
                    continue
                seen_tools.add(tool)

                results.append(
                    {
                        "tool": tool,
                        "path": file_path,
                        "date": prov.get("date", "unknown"),
                        "model": prov.get("model", "unknown"),
                    }
                )

    return sorted(results, key=lambda x: x["tool"])


def reconcile(config: Config | None = None) -> dict[str, Entry]:
    """Return every entry after bringing the manifest back in step with the disk.

    Seeds from provenance headers when no manifest file exists yet, and
    persists that seed so it runs once.  Then converts recoverable legacy
    copies into owned links (ADR-0028) and verified vendor copies into direct
    provider links (ADR-0032), saving only when something moved.

    Write paths call this; `manifest.load` never does, so a read-only command
    observes the manifest exactly as persisted.
    """
    cfg = config or Config()
    seeding = not cfg.manifest_path.exists()
    entries = _seed_from_headers(cfg) if seeding else manifest.load(cfg)

    migrated = _migrate_links(entries, cfg)
    if _migrate_install_root_links(entries, cfg):
        migrated = True
    if seeding or migrated:
        manifest.save(entries, cfg)
    return entries


def materialize_target(src: Path, config: Config, *, durable_source: bool) -> Path:
    """Return an upgrade-safe link target, materializing it before link replacement."""
    if durable_source:
        return src.absolute()
    target = config.output_dir / src.name
    if src.absolute() == target.absolute():
        return target
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary_target = target.with_name(f".{target.name}.tmp")
    shutil.copy2(src, temporary_target)
    temporary_target.replace(target)
    return target


def link_manpath_entry(path: Path, target: Path) -> None:
    """Point a manpath entry at `target`, replacing whatever occupies it atomically."""
    temporary_link = path.with_name(f".{path.name}.maniac.tmp")
    temporary_link.symlink_to(target)
    temporary_link.replace(path)


def discard_durable_target(entry: Entry, config: Config) -> Path | None:
    """Remove the MANIAC-owned target an uninstalled entry leaves behind, if any.

    Returns the removed path, or None when nothing was MANIAC's to remove --
    a provider-owned target is never deleted (ADR-0031).
    """
    if entry.target is None or entry.provider_target:
        return None
    target = manifest.expected_target_path(entry)
    if not manifest.is_maniac_owned_target(target, config) or not target.exists():
        return None
    target.unlink()
    return target


def _seed_from_headers(config: Config) -> dict[str, Entry]:
    """Migrate pre-ADR-0017 state: a page carrying a provenance header was synthesized.

    Tiers 1 and 2 copy their page verbatim and carry no header, so they are
    not recoverable here -- accepted in ADR-0017 as the cost of migration,
    since they already reported foreign under the code this replaces.

    `list_installed_manpages` also scans `output_dir`, a staging copy of
    what synthesis produced, not proof anything is on the manpath -- a page
    seeded from there rather than `man_dir` would report MANAGED for a tool
    with nothing installed, so only a `man_dir` hit is kept.
    """
    entries = {
        item["tool"]: Entry(
            path=item["path"],
            tier=Tier.SYNTHESIS,
            source=item["model"],
            checksum=manifest.checksum_of(item["path"]),
        )
        for item in list_installed_manpages(config)
        if item["path"].parent == config.man_dir
    }
    _migrate_backups(entries, config)
    return entries


def _migrate_backups(entries: dict[str, Entry], config: Config) -> None:
    """Relocate stray `.maniac_bak` files out of `man_dir`, attributed by matching filename.

    Repairs the pre-ADR-0017 bug where a backup's name (`dest_file.name`
    plus `.maniac_bak`) never matched what restore reconstructed
    (`f"{tool_name}.1.maniac_bak"`), so a backup of a compressed page was
    created and never found. A backup matching no entry's destination
    filename is left where it is -- nothing on record to attribute it to.
    """
    if not config.man_dir.exists():
        return
    by_filename = {entry.path.name: tool for tool, entry in entries.items()}
    for backup_file in config.man_dir.glob("*.maniac_bak"):
        original_name = backup_file.name.removesuffix(".maniac_bak")
        tool = by_filename.get(original_name)
        if tool is None:
            continue
        config.backup_dir.mkdir(parents=True, exist_ok=True)
        destination = config.backup_dir / original_name
        # shutil.move, not Path.rename: man_dir (XDG_DATA_HOME) and
        # backup_dir (XDG_STATE_HOME) can be separate mounts, where a bare
        # rename raises EXDEV.
        shutil.move(backup_file, destination)
        entries[tool] = replace(entries[tool], backup=destination)


def _migrate_links(entries: dict[str, Entry], config: Config) -> bool:
    """Convert safely recoverable pre-ADR-0028 copies into owned links.

    The installed copy is the only trustworthy bytes source for an older
    entry.  It is materialized under MANIAC's durable output directory before
    replacing the manpath path.  A changed, missing, or pre-existing-link
    entry is deliberately retained: guessing at its provenance could destroy
    a usable user page.
    """
    migrated = False
    for tool, entry in entries.items():
        if entry.target is not None:
            continue
        path = entry.path
        if path.is_symlink() or not path.is_file():
            logger.warning(
                "Retained unsafe legacy manpage entry", tool=tool, path=str(path)
            )
            continue
        try:
            if manifest.checksum_of(path) != entry.checksum:
                logger.warning(
                    "Retained changed legacy manpage entry", tool=tool, path=str(path)
                )
                continue
            target = materialize_target(path, config, durable_source=False)
            link_manpath_entry(path, target)
        except OSError as error:
            logger.warning(
                "Retained legacy manpage entry after migration failure",
                tool=tool,
                path=str(path),
                error=str(error),
            )
            continue
        entries[tool] = replace(entry, target=target)
        migrated = True
    return migrated


def _migrate_install_root_links(entries: dict[str, Entry], config: Config) -> bool:
    """Replace safely identified durable vendor copies with direct provider links."""
    target_users: dict[Path, int] = {}
    for entry in entries.values():
        if entry.target is None:
            continue
        target = manifest.expected_target_path(entry).absolute()
        if manifest.is_maniac_owned_target(target, config):
            target_users[target] = target_users.get(target, 0) + 1

    migrated = False
    for tool, entry in entries.items():
        migrated_entry = _migrate_install_root_entry(tool, entry, config, target_users)
        if migrated_entry is None:
            continue
        entries[tool] = migrated_entry
        migrated = True
    return migrated


def _migrate_install_root_entry(
    tool: str, entry: Entry, config: Config, target_users: dict[Path, int]
) -> Entry | None:
    """Return a direct-provider entry after safely relinking one durable vendor copy."""
    if (
        entry.tier is not Tier.INSTALL_ROOT
        or entry.provider_target
        or not manifest.is_expected_link(entry)
    ):
        return None
    old_target = manifest.expected_target_path(entry)
    if not manifest.is_maniac_owned_target(old_target, config):
        return None
    try:
        if manifest.checksum_of(old_target) != entry.checksum:
            return None
        root = Path(entry.source).expanduser()
        if not root.is_dir():
            return None
        page = select_primary_manpage(find_install_root_manpages(root, tool), tool)
        if page is None:
            return None
        resolved_root = resolve_cached(root)
        resolve_cached(page).relative_to(resolved_root)
        if manifest.is_maniac_owned_target(page, config):
            return None
        page_checksum = manifest.checksum_of(page)
    except (OSError, ValueError):
        return None

    try:
        link_manpath_entry(entry.path, page.absolute())
    except OSError as error:
        logger.warning(
            "Retained durable vendor manpage after migration failure",
            tool=tool,
            path=str(entry.path),
            error=str(error),
        )
        return None

    if target_users[old_target.absolute()] == 1:
        try:
            old_target.unlink()
        except OSError as error:
            logger.warning(
                "Retained superseded durable vendor target",
                tool=tool,
                path=str(old_target),
                error=str(error),
            )
    return replace(
        entry,
        checksum=page_checksum,
        target=page.absolute(),
        provider_target=True,
    )
