"""Filesystem lifecycle of MANIAC-managed manpath entries (ADR-0028, ADR-0031, ADR-0032).

Every transition a managed page can undergo lives here: recovering legacy
copies, migrating verified vendor copies to direct provider links,
materializing durable targets, replacing manpath links and removing
superseded ones.  `manifest` only serializes; nothing in this module runs as
an effect of deserializing it.
"""

import shutil
from dataclasses import replace
from pathlib import Path

from . import manifest
from .config import Config
from .logging import logger
from .manifest import Entry, Tier
from .sources.candidates import select_historical_install_root

PROVENANCE_SIGNATURE = r".\" Generated by MANIAC (https://github.com/susensio/maniac)"


def reconcile(
    txn: manifest.Transaction, *, removed: list[Path] | None = None
) -> dict[str, Entry]:
    """Return `txn`'s entries after bringing them back in step with the disk.

    Relocates stray pre-ADR-0017 backups, converts recoverable legacy copies into owned links
    (ADR-0028) and verified vendor copies into direct provider links
    (ADR-0032), marking
    the transaction dirty only when something moved.  What it returns is
    `txn.entries` itself, so a caller that mutates the manifest further
    mutates the same working set.

    Write paths call this inside their transaction; `manifest.load` never
    does, so a read-only command observes the manifest exactly as persisted.

    `removed` collects every path migration deletes, for a caller that reports
    its own removals.  Omitting it deletes the same files silently, which is
    what a caller with no removal report to write into gets; `install` is the
    only such caller, since ADR-0034 routed `list` through `manifest.load`
    and nothing read-only reconciles at all.
    """
    _migrate_backups(txn)
    _migrate_links(txn)
    _migrate_install_root_links(txn, removed)
    return txn.entries


def materialize_target(
    src: Path,
    config: Config,
    *,
    durable_source: bool,
    entries: dict[str, Entry],
    tool: str,
) -> Path:
    """Return an upgrade-safe link target, materializing it before link replacement.

    The durable target is named after the source page, so two tools whose
    pages share a basename resolve to one path.  Writing it would replace a
    second entry's recorded bytes, and that entry's checksum would then
    mismatch forever -- leaving it un-uninstallable.  A collision is refused
    by name rather than renamed around: the durable name is derived, nothing
    reads a disambiguated one back, and a page arriving under two manifest
    keys is a mistake worth surfacing.
    """
    if durable_source:
        return src.absolute()
    target = config.output_dir / src.name
    owner = _recorded_target_owner(target, entries, config, tool)
    if owner is not None:
        raise FileExistsError(
            f"The durable target '{target}' is already recorded by '{owner}'. "
            f"Uninstall '{owner}' or rename the source page before installing "
            f"'{tool}'."
        )
    if src.absolute() == target.absolute():
        return target
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary_target = target.with_name(f".{target.name}.tmp")
    shutil.copy2(src, temporary_target)
    temporary_target.replace(target)
    return target


def target_users(entries: dict[str, Entry], config: Config) -> dict[Path, list[str]]:
    """Which tools record each MANIAC-owned durable target, keyed by absolute path.

    One durable target can carry more than one entry, so every decision to
    write or delete one asks this first.
    """
    users: dict[Path, list[str]] = {}
    for tool, entry in entries.items():
        if entry.target is None:
            continue
        target = manifest.expected_target_path(entry).absolute()
        if manifest.is_maniac_owned_target(target, config):
            users.setdefault(target, []).append(tool)
    return users


def _recorded_target_owner(
    target: Path, entries: dict[str, Entry], config: Config, tool: str
) -> str | None:
    """Name of another tool whose entry already records `target`, or None."""
    users = target_users(entries, config).get(target.absolute(), [])
    return next((other for other in users if other != tool), None)


def link_manpath_entry(path: Path, target: Path) -> None:
    """Point a manpath entry at `target`, replacing whatever occupies it atomically."""
    temporary_link = path.with_name(f".{path.name}.maniac.tmp")
    temporary_link.unlink(missing_ok=True)
    try:
        temporary_link.symlink_to(target)
        temporary_link.replace(path)
    except OSError:
        # A staged link nothing reached is invisible litter on the manpath;
        # `man` would still scan it.
        temporary_link.unlink(missing_ok=True)
        raise


def discard_durable_target(
    entry: Entry, config: Config, entries: dict[str, Entry]
) -> Path | None:
    """Remove the MANIAC-owned target an uninstalled entry leaves behind, if any.

    Returns the removed path, or None when nothing was MANIAC's to remove --
    a provider-owned target is never deleted (ADR-0031), and neither is one
    another entry in `entries` still records.  `entries` holds what remains
    after `entry`'s own record is forgotten; unlinking a shared target would
    dangle the other entry's link and leave its checksum unverifiable, so it
    could never be uninstalled either.
    """
    if entry.target is None or entry.provider_target:
        return None
    target = manifest.expected_target_path(entry)
    if not manifest.is_maniac_owned_target(target, config) or not target.exists():
        return None
    sharers = target_users(entries, config).get(target.absolute(), [])
    if sharers:
        logger.info(
            "Retained durable target still recorded elsewhere",
            path=str(target),
            tools=sharers,
        )
        return None
    target.unlink()
    return target


def _migrate_backups(txn: manifest.Transaction) -> None:
    """Relocate stray `.maniac_bak` files out of `man_dir`, attributed by matching filename.

    Repairs the pre-ADR-0017 bug where a backup's name (`dest_file.name`
    plus `.maniac_bak`) never matched what restore reconstructed
    (`f"{tool_name}.1.maniac_bak"`), so a backup of a compressed page was
    created and never found. A backup matching no entry's destination
    filename is left where it is -- nothing on record to attribute it to.
    """
    config = txn.config
    if not config.man_dir.exists():
        return
    by_filename = {entry.path.name: tool for tool, entry in txn.entries.items()}
    for backup_file in config.man_dir.glob("*.maniac_bak"):
        original_name = backup_file.name.removesuffix(".maniac_bak")
        tool = by_filename.get(original_name)
        if tool is None:
            continue
        config.backup_dir.mkdir(parents=True, exist_ok=True)
        destination = config.backup_dir / original_name
        # shutil.move, not Path.rename: man_dir (XDG_DATA_HOME) and
        # backup_dir (XDG_STATE_HOME) can be separate mounts, where a bare
        # rename raises EXDEV.
        shutil.move(backup_file, destination)
        txn.put(tool, replace(txn.entries[tool], backup=destination))


def _migrate_links(txn: manifest.Transaction) -> None:
    """Convert safely recoverable pre-ADR-0028 copies into owned links.

    The installed copy is the only trustworthy bytes source for an older
    entry.  It is materialized under MANIAC's durable output directory before
    replacing the manpath path.  A changed, missing, or pre-existing-link
    entry is deliberately retained: guessing at its provenance could destroy
    a usable user page.
    """
    entries = txn.entries
    config = txn.config
    for tool, entry in list(entries.items()):
        if entry.target is not None:
            continue
        path = entry.path
        if path.is_symlink():
            recovered = _migrated_link(entry, config)
            if recovered is None:
                logger.warning(
                    "Retained unsafe legacy manpage entry", tool=tool, path=str(path)
                )
                continue
            txn.put(tool, recovered)
            continue
        if not path.is_file():
            logger.warning(
                "Retained unsafe legacy manpage entry", tool=tool, path=str(path)
            )
            continue
        try:
            if manifest.checksum_of(path) != entry.checksum:
                logger.warning(
                    "Retained changed legacy manpage entry", tool=tool, path=str(path)
                )
                continue
            target = materialize_target(
                path, config, durable_source=False, entries=entries, tool=tool
            )
            link_manpath_entry(path, target)
        except OSError as error:
            logger.warning(
                "Retained legacy manpage entry after migration failure",
                tool=tool,
                path=str(path),
                error=str(error),
            )
            continue
        txn.put(tool, replace(entry, target=target))


def _migrated_link(entry: Entry, config: Config) -> Entry | None:
    """Return the entry a completed-but-unrecorded migration left, or None.

    A migration that linked the page and then failed before its manifest
    write leaves a targetless record beside a symlink into `output_dir`.
    The recorded checksum is the migrated bytes' own, so a match proves the
    link is that migration's and not a page someone else substituted.
    """
    try:
        target = entry.path.readlink()
        resolved = target if target.is_absolute() else entry.path.parent / target
        if not manifest.is_maniac_owned_target(resolved, config):
            return None
        if not resolved.is_file() or manifest.checksum_of(resolved) != entry.checksum:
            return None
    except OSError:
        return None
    return replace(entry, target=target)


def _migrate_install_root_links(
    txn: manifest.Transaction, removed: list[Path] | None
) -> None:
    """Replace safely identified durable vendor copies with direct provider links."""
    users = target_users(txn.entries, txn.config)
    for tool, entry in list(txn.entries.items()):
        migrated_entry = _migrate_install_root_entry(
            tool, entry, txn.config, users, removed
        )
        if migrated_entry is None:
            continue
        txn.put(tool, migrated_entry)


def _migrate_install_root_entry(
    tool: str,
    entry: Entry,
    config: Config,
    target_users: dict[Path, list[str]],
    removed: list[Path] | None,
) -> Entry | None:
    """Return a direct-provider entry after safely relinking one durable vendor copy."""
    if (
        entry.tier is not Tier.INSTALL_ROOT
        or entry.provider_target
        # BUG: an ADR-0032 migration interrupted between relinking and its
        # manifest write leaves the recorded target deleted, so this guard
        # skips that entry forever and uninstall reports it MODIFIED.
        or not manifest.is_expected_link(entry)
    ):
        return None
    old_target = manifest.expected_target_path(entry)
    if not manifest.is_maniac_owned_target(old_target, config):
        return None
    try:
        if manifest.checksum_of(old_target) != entry.checksum:
            return None
        root = Path(entry.source).expanduser()
        if not root.is_dir():
            return None
        candidate = select_historical_install_root(root, tool)
        if candidate is None or not candidate.provider_owned:
            return None
        page = candidate.primary.path
        if manifest.is_maniac_owned_target(page, config):
            return None
        page_checksum = manifest.checksum_of(page)
    except (OSError, ValueError):
        return None

    try:
        link_manpath_entry(entry.path, page.absolute())
    except OSError as error:
        logger.warning(
            "Retained durable vendor manpage after migration failure",
            tool=tool,
            path=str(entry.path),
            error=str(error),
        )
        return None

    if target_users[old_target.absolute()] == [tool]:
        try:
            old_target.unlink()
            if removed is not None:
                removed.append(old_target)
        except OSError as error:
            logger.warning(
                "Retained superseded durable vendor target",
                tool=tool,
                path=str(old_target),
                error=str(error),
            )
    return replace(
        entry,
        checksum=page_checksum,
        target=page.absolute(),
        provider_target=True,
    )
