"""Track which pages MANIAC installed (ADR-0017, ADR-0028).

The manifest, not a page's own bytes, is what `install`, `uninstall` and
`status` consult to decide ownership.  Its recorded target establishes the
expected manpath link.  A provenance header never establishes ownership; it
only tells recovery which tier a page it already owns came from.
"""

import fcntl
import hashlib
import json
import os
import re
import threading
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass, field, replace
from enum import Enum
from pathlib import Path
from typing import Any

from .config import Config
from .logging import logger

# A floor, not an equality: a manifest stamped at or below this version is
# readable, so the field can be bumped whenever a change needs a reader to
# know which shape it is holding.  Only a *newer* stamp than this build
# understands is refused, and it is refused as damaged -- never as empty.
# Absent and unparseable stamps are damaged too: an unstamped document is
# not a version-0 document, it is one whose shape nothing vouches for.
SCHEMA_VERSION = 1
# Generation stamps this on every page it writes, and recovery is the only
# reader: it separates a synthesized page from a repository page copied
# verbatim, both of which live under `output_dir`.
PROVENANCE_SIGNATURE = (
    r""".\" Generated by MANIAC (https://github.com/susensio/maniac)"""
)
_CHUNK_SIZE = 65_536
_CHECKPOINT_SUFFIX = ".good"
_LOCK_SUFFIX = ".lock"
_RECONSTRUCTED_SOURCE = "reconstructed"
_COMPRESSION_SUFFIXES = {".gz", ".bz2", ".xz", ".zst"}
_SECTION_DIRECTORY = re.compile(r"man\d+")


class Tier(Enum):
    """Which of ADR-0016's three source tiers produced a manifest entry."""

    INSTALL_ROOT = "install_root"
    REPOSITORY = "repository"
    SYNTHESIS = "synthesis"


@dataclass(frozen=True, slots=True)
class Entry:
    """One tool's manifest record: where its page lives, how it got there, and its bytes' hash.

    `backup` is the path of the vendor page `install_manpage --force` backed
    up before overwriting, under `Config.backup_dir` -- or None when install
    found the destination empty and took no backup, distinct from "unknown".
    `checksum` is the sha256 hex digest taken from the source file before
    the durable target that installed it -- materialization is byte-identical,
    so it is also the target's digest.
    `version` is the tool version the page documents, None where nothing
    was known to record -- including every entry written before this field
    existed (ADR-0018).
    `source_uri` is the exact upstream file or release asset URI for a
    repository-tier page; older entries and other tiers leave it None.
    `target` is the expected target of the owned manpath symlink.  It is
    absent only on entries written before ADR-0028 that migration could not
    safely convert.
    `provider_target` marks a validated provider-managed target whose bytes
    may advance independently of MANIAC.
    `group` names the manifest key of the primary page of the upstream
    release these pages arrived in, carried by every member including the
    primary itself -- so membership and primacy are one field, and
    uninstalling a companion reaches the same unit as uninstalling the
    primary.  None on a page that arrived alone and on every entry written
    before this field existed (ADR-0018).
    """

    path: Path
    tier: Tier
    source: str
    checksum: str
    backup: Path | None = None
    version: str | None = None
    source_uri: str | None = None
    target: Path | None = None
    provider_target: bool = False
    group: str | None = None


def manpage_owner(page: Path) -> str:
    """Return the manifest key a manpage filename belongs to.

    The name without its section or compression suffix, so `foo.bar.1.gz`
    is `foo.bar`.  Install derives a key this way and recovery has to agree,
    or a recovered entry answers to a name nothing looks it up under.
    """
    path = page.with_suffix("") if page.suffix in _COMPRESSION_SUFFIXES else page
    return path.with_suffix("").name


def checksum_of(path: str | Path) -> str:
    """Return the sha256 hex digest of a file's contents."""
    digest = hashlib.sha256()
    with Path(path).open("rb") as f:
        for chunk in iter(lambda: f.read(_CHUNK_SIZE), b""):
            digest.update(chunk)
    return digest.hexdigest()


def expected_target_path(entry: Entry) -> Path:
    """Return a recorded target resolved from its manpath entry."""
    assert entry.target is not None
    return (
        entry.target if entry.target.is_absolute() else entry.path.parent / entry.target
    )


def is_expected_link(entry: Entry) -> bool:
    """Whether a manpath entry still points literally to its recorded target."""
    if entry.target is None or not entry.path.is_symlink():
        return False
    try:
        if entry.path.readlink() != entry.target:
            return False
    except OSError:
        return False
    return expected_target_path(entry).exists()


def is_maniac_owned_target(target: Path | None, config: Config) -> bool:
    """Whether a target belongs to MANIAC's durable output storage."""
    if target is None:
        return False
    try:
        target.absolute().relative_to(config.output_dir.absolute())
    except ValueError:
        return False
    return True


def _manifest_path(config: Config | None) -> Path:
    return (config or Config()).manifest_path


def _entry_to_row(entry: Entry) -> dict[str, Any]:
    return {
        "path": str(entry.path),
        "tier": entry.tier.value,
        "source": entry.source,
        "checksum": entry.checksum,
        "backup": str(entry.backup) if entry.backup is not None else None,
        "version": entry.version,
        "source_uri": entry.source_uri,
        "target": str(entry.target) if entry.target is not None else None,
        "provider_target": entry.provider_target,
        "group": entry.group,
    }


def _row_to_entry(row: Any) -> Entry:
    """Return the entry a row describes.

    Raises KeyError, TypeError or ValueError for anything malformed -- a
    missing key, a wrong type, an unrecognized tier.
    """
    if not isinstance(row, dict):
        raise TypeError(f"row is {type(row).__name__}, not an object")
    backup = row["backup"]
    raw_source_uri = row.get("source_uri")
    raw_target = row.get("target")
    raw_group = row.get("group")
    source_uri = (
        raw_source_uri
        if isinstance(raw_source_uri, str)
        and raw_source_uri.startswith(("https://", "http://", "file://"))
        else None
    )
    return Entry(
        path=Path(row["path"]),
        tier=Tier(row["tier"]),
        source=row["source"],
        checksum=row["checksum"],
        backup=Path(backup) if backup is not None else None,
        # .get, not []: absent on every row written before this field
        # existed (ADR-0018), and that must read as None, not fail to parse.
        version=row.get("version"),
        source_uri=source_uri,
        target=Path(raw_target) if isinstance(raw_target, str) else None,
        provider_target=row.get("provider_target") is True,
        # .get again (ADR-0018): a row written before groups existed must
        # read as ungrouped, not fail to parse.
        group=raw_group if isinstance(raw_group, str) else None,
    )


class Link(Enum):
    """What the filesystem says about one entry's manpath link."""

    # Manpath entry is a symlink to the recorded target, and it exists.
    SOUND = "sound"
    # Pre-ADR-0028 entry: no recorded target to check, page present.
    UNVERIFIABLE = "unverifiable"
    # Nothing there, not a symlink, pointed elsewhere, or dangling.
    BROKEN = "broken"


def link_state(entry: Entry) -> Link:
    """Return what the disk says about one entry, by `lstat` and `readlink` only."""
    if entry.target is None:
        return Link.UNVERIFIABLE if entry.path.is_file() else Link.BROKEN
    return Link.SOUND if is_expected_link(entry) else Link.BROKEN


def scan(entries: dict[str, Entry]) -> dict[str, Link]:
    """Return every entry's link state, keyed by tool.

    Pure `lstat`/`readlink` over what MANIAC owns, never over `$PATH` --
    the manifest holds a handful of entries where `$PATH` holds dozens of
    binaries, so the cost is proportional to what was installed and stays
    microseconds per entry.  Cheap enough to run on every read rather than
    behind a flag.
    """
    return {tool: link_state(entry) for tool, entry in entries.items()}


class Health(Enum):
    """How much of the manifest a read recovered."""

    ABSENT = "absent"
    INTACT = "intact"
    DAMAGED = "damaged"


@dataclass(frozen=True, slots=True)
class Read:
    """What a manifest read recovered, and whether that is all there was.

    `entries` holds every row that deserialized, which is the best record
    available whatever the health: `backup`, `source_uri` and `version` have
    no filesystem evidence, so a salvaged row is unrecoverable elsewhere.
    `reason` names a whole-document failure -- unreadable file, bad JSON,
    wrong shape, a stamp newer than this build reads -- and is None when the
    document itself was fine.
    `lost` maps the tool key of each skipped row to why it was skipped.  A
    single lost key is enough to make the read DAMAGED: ownership that
    silently evaporates is written out permanently by the next save.
    `links` maps each recovered entry to what the disk says about its
    manpath link.  Health is about the document; this is about the pages it
    names, and a row can parse perfectly while its page is gone.
    """

    entries: dict[str, Entry]
    health: Health
    reason: str | None = None
    lost: dict[str, str] = field(default_factory=dict)
    links: dict[str, Link] = field(default_factory=dict)


def _damaged(reason: str) -> Read:
    return Read(entries={}, health=Health.DAMAGED, reason=reason)


def read(config: Config | None = None) -> Read:
    """Return the manifest's entries, the verdict on how complete they are, and their link states.

    Read-only, which is what ADR-0034 asks of it: the structural scan
    `lstat`s and `readlink`s what the entries name and mutates nothing, so
    `maniac list` learns about drift at the moment it reads rather than
    whenever the next install happens to open a transaction.  Promotion does
    mutate and stays out, in `promote`, which write paths call explicitly.
    """
    document = _read_document(_manifest_path(config))
    return replace(document, links=scan(document.entries))


def _read_document(path: Path) -> Read:
    """Return what one manifest-shaped document at `path` yields."""
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return Read(entries={}, health=Health.ABSENT)
    except OSError as exc:
        return _damaged(f"unreadable: {exc}")
    try:
        document = json.loads(text)
    except json.JSONDecodeError as exc:
        return _damaged(f"invalid JSON: {exc}")
    if not isinstance(document, dict):
        return _damaged(f"document is {type(document).__name__}, not an object")

    stored = document.get("version")
    if not isinstance(stored, int) or isinstance(stored, bool):
        return _damaged(f"schema version is {stored!r}, not an integer")
    if stored > SCHEMA_VERSION:
        return _damaged(
            f"schema version {stored} is newer than this build reads ({SCHEMA_VERSION})"
        )

    raw_entries = document.get("entries")
    if not isinstance(raw_entries, dict):
        return _damaged(f"entries is {type(raw_entries).__name__}, not an object")

    entries: dict[str, Entry] = {}
    lost: dict[str, str] = {}
    for tool, row in raw_entries.items():
        try:
            entries[tool] = _row_to_entry(row)
        except (KeyError, TypeError, ValueError) as exc:
            lost[tool] = f"{type(exc).__name__}: {exc}"
    if lost:
        return Read(entries=entries, health=Health.DAMAGED, lost=lost)
    return Read(entries=entries, health=Health.INTACT)


def load(config: Config | None = None) -> dict[str, Entry]:
    """Return every recorded entry, keyed by tool.

    The entries of `read`, without its verdict: for callers that only need
    the records and have no answer to a partial loss.  Anything that decides
    what to do about damage wants `read` instead.
    """
    return read(config).entries


def _write_document(path: Path, document: dict[str, Any]) -> None:
    """Write `document` to `path` durably: temp file, fsync, rename, fsync dir.

    The rename alone survives a process crash but not a power loss, which
    can land the directory entry ahead of the data (ADR-0043).
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = path.with_name(path.name + ".tmp")
    with temporary_path.open("w", encoding="utf-8") as f:
        json.dump(document, f, indent=2, sort_keys=True)
        f.flush()
        os.fsync(f.fileno())
    temporary_path.replace(path)
    directory = os.open(path.parent, os.O_RDONLY)
    try:
        os.fsync(directory)
    finally:
        os.close(directory)


def _document(entries: dict[str, Entry]) -> dict[str, Any]:
    return {
        "version": SCHEMA_VERSION,
        "entries": {tool: _entry_to_row(entry) for tool, entry in entries.items()},
    }


def save(entries: dict[str, Entry], config: Config | None = None) -> None:
    """Persist `entries` as the whole manifest, replacing what it held."""
    _write_document(_manifest_path(config), _document(entries))


def checkpoint_path(config: Config | None = None) -> Path:
    """Return the `.good` checkpoint path beside the manifest."""
    path = _manifest_path(config)
    return path.with_name(path.name + _CHECKPOINT_SUFFIX)


def promote(read_result: Read, config: Config | None = None) -> bool:
    """Whether `read_result` was promoted to the `.good` checkpoint.

    Only an INTACT read promotes.  A damaged one leaves the existing
    checkpoint untouched -- that refusal is the whole mechanism, and it is
    what stops rot from overwriting the last known-good copy.

    Callers hold the promotion decision, so the structural scan that carries
    more evidence than the read does -- an entry whose page vanished parses
    perfectly -- gates the call rather than being threaded through here.
    """
    if read_result.health is not Health.INTACT:
        return False
    _write_document(checkpoint_path(config), _document(read_result.entries))
    return True


def lookup(tool: str, config: Config | None = None) -> Entry | None:
    """Return `tool`'s recorded entry, or None if MANIAC never installed it."""
    return load(config).get(tool)


@dataclass(frozen=True, slots=True)
class Recovery:
    """What rebuilding an untrustworthy manifest adopted, and from where.

    `reconstructed` names the tools no record survived for.  `backup`,
    `source_uri` and `version` have no filesystem evidence, so those entries
    carry none: uninstalling one cannot restore a vendor page it displaced.
    That loss is why the checkpoint is kept at all.
    `dropped` names checkpoint records the disk refused -- the page is gone,
    which is what a legitimate uninstall since the checkpoint looks like.
    """

    reason: str
    salvaged: tuple[str, ...] = ()
    from_checkpoint: tuple[str, ...] = ()
    reconstructed: tuple[str, ...] = ()
    dropped: tuple[str, ...] = ()


def read_provenance_header(file_path: str | Path) -> dict[str, str] | None:
    """Read provenance metadata from the header of a roff manpage file."""
    path = Path(file_path)
    if not path.exists() or not path.is_file():
        return None

    try:
        with path.open("r", encoding="utf-8", errors="replace") as f:
            first_line = f.readline().strip()
            if first_line != PROVENANCE_SIGNATURE:
                return None
            second_line = f.readline().strip()
    except PermissionError:
        # Distinguish "can't read it" from "read it, not ours" -- the caller
        # should not treat a permission failure as a foreign/vendor page.
        logger.warning("Permission denied reading manpage header", path=str(path))
        raise
    except OSError:
        return None

    metadata = {"tool": path.stem, "date": "unknown", "model": "unknown"}
    if second_line.startswith(r".\" "):
        meta_content = second_line[4:].strip()
        for item in meta_content.split("|"):
            parts = item.split(":", 1)
            if len(parts) == 2:
                key = parts[0].strip().lower()
                val = parts[1].strip()
                metadata[key] = val

    return metadata


def _provenance_of(target: Path) -> tuple[Tier, str]:
    """Return the tier and source a durable target's own header discriminates.

    Synthesis stamps every page it writes; a tier-2 page is copied verbatim
    from upstream and carries no stamp.  That is the only question asked
    here.  Ownership is already settled by the link target before this runs
    (ADR-0028, ADR-0044) -- the header never seeds it, which is what
    `_seed_from_headers` did and was deleted for.
    """
    try:
        header = read_provenance_header(target)
    except PermissionError:
        # Unreadable header is no observed header, and an unstamped page
        # under `output_dir` is tier 2.  Degrading here rather than raising
        # keeps one bad file from failing the whole recovery.
        header = None
    if header is None:
        return Tier.REPOSITORY, _RECONSTRUCTED_SOURCE
    model = header.get("model", "unknown")
    return Tier.SYNTHESIS, _RECONSTRUCTED_SOURCE if model == "unknown" else model


def _entry_from_link(path: Path, config: Config) -> Entry | None:
    """Return the entry one manpath symlink proves, or None if it proves nothing.

    Only a target under `output_dir` proves anything: nothing else writes
    there, so the page was materialized by an install whose record never
    landed (ADR-0028).  A link to anywhere else is indistinguishable from
    one the user made by hand, and adopting it would authorize MANIAC to
    replace and remove a file it never installed -- so a tier-1 direct
    provider link is not reconstructible, and its page reads as foreign
    until a `--force` install records it again.
    """
    try:
        target = path.readlink()
        resolved = target if target.is_absolute() else path.parent / target
        if not resolved.is_file() or not is_maniac_owned_target(resolved, config):
            return None
        checksum = checksum_of(resolved)
    except OSError:
        return None
    # Backups are named after the entry they displaced, which is what makes
    # one traceable without a journal (ADR-0043).
    backup = config.backup_dir / path.name
    tier, source = _provenance_of(resolved)
    return Entry(
        path=path,
        tier=tier,
        source=source,
        checksum=checksum,
        backup=backup if backup.is_file() else None,
        target=target,
    )


def _section_directories(config: Config) -> list[Path]:
    """Return every `manN` directory MANIAC installs into, `man_dir` included.

    A multi-page release puts its section-5 and section-8 companions in
    `man_dir`'s siblings, and a scan of `man1` alone would leave them
    unrecoverable.
    """
    root = config.man_dir.parent
    if not root.is_dir():
        return []
    return sorted(
        directory
        for directory in root.iterdir()
        if directory.is_dir() and _SECTION_DIRECTORY.fullmatch(directory.name)
    )


def _linked_entries(config: Config) -> dict[str, Entry]:
    """Return an entry for every manpath symlink whose target proves MANIAC linked it."""
    entries: dict[str, Entry] = {}
    for directory in _section_directories(config):
        for path in sorted(directory.iterdir()):
            if not path.is_symlink():
                continue
            entry = _entry_from_link(path, config)
            if entry is not None:
                entries[manpage_owner(path)] = entry
    return entries


def _adopt_orphans(entries: dict[str, Entry], config: Config) -> tuple[str, ...]:
    """Adopt every unrecorded manpath symlink into `output_dir`, naming what was adopted.

    An install that crashed between linking and recording leaves exactly
    this, and leaving it unrecorded makes MANIAC's own page read as foreign
    on the next install of that tool.
    """
    recorded = {entry.path.absolute() for entry in entries.values()}
    adopted = {
        tool: entry
        for tool, entry in _linked_entries(config).items()
        if tool not in entries and entry.path.absolute() not in recorded
    }
    entries.update(adopted)
    return tuple(sorted(adopted))


def _recover(current: Read, config: Config) -> tuple[dict[str, Entry], Recovery]:
    """Rebuild a manifest from every source with evidence, strongest first.

    Salvaged rows win: they are the most recent state, and `backup`,
    `source_uri` and `version` exist nowhere else.  The checkpoint fills
    tools the damaged file lost, but only where the disk still agrees with
    it -- a checkpoint record whose page is gone is an uninstall that
    happened after the checkpoint, and resurrecting it would authorize
    MANIAC to delete a page it no longer owns.  The link scan fills whatever
    neither supplies.
    """
    entries = dict(current.entries)
    checkpoint = _read_document(checkpoint_path(config))
    adopted: list[str] = []
    dropped: list[str] = []
    for tool, entry in sorted(checkpoint.entries.items()):
        if tool in entries:
            continue
        if link_state(entry) is Link.BROKEN:
            dropped.append(tool)
            continue
        entries[tool] = entry
        adopted.append(tool)

    reconstructed: list[str] = []
    recorded = {entry.path.absolute() for entry in entries.values()}
    for tool, entry in sorted(_linked_entries(config).items()):
        # One manpath path has one owner: a link a surviving record already
        # names is that record's, whatever key the filename suggests.
        if tool in entries or entry.path.absolute() in recorded:
            continue
        entries[tool] = entry
        reconstructed.append(tool)

    return entries, Recovery(
        reason=current.reason or _damage_reason(current),
        salvaged=tuple(sorted(current.entries)),
        from_checkpoint=tuple(adopted),
        reconstructed=tuple(reconstructed),
        dropped=tuple(dropped),
    )


def _damage_reason(current: Read) -> str:
    """Name the damage when the document itself parsed."""
    if current.health is Health.ABSENT:
        return "no manifest file"
    return f"unreadable rows: {', '.join(sorted(current.lost))}"


def _report_recovery(recovery: Recovery, config: Config) -> None:
    """Log what recovery adopted, and per tool what it could not recover."""
    logger.warning(
        "Rebuilt an untrustworthy manifest",
        reason=recovery.reason,
        manifest=str(_manifest_path(config)),
        salvaged=list(recovery.salvaged),
        from_checkpoint=list(recovery.from_checkpoint),
        reconstructed=list(recovery.reconstructed),
        dropped=list(recovery.dropped),
    )
    for tool in recovery.reconstructed:
        logger.warning(
            "Reconstructed a manifest entry from its link alone",
            tool=tool,
            unrecoverable=["backup", "source_uri", "version"],
            consequence="uninstall cannot restore a vendor page this page displaced",
        )


_transaction_locks: dict[Path, threading.Lock] = {}
_transaction_locks_guard = threading.Lock()


def lock_path(config: Config | None = None) -> Path:
    """Return the lock file serializing manifest writers, beside the manifest."""
    path = _manifest_path(config)
    return path.with_name(path.name + _LOCK_SUFFIX)


@contextmanager
def _exclusive(config: Config) -> Iterator[None]:
    """Serialize manifest writers across threads and processes.

    `flock` alone serializes processes but not two threads sharing one
    descriptor, so a process-local lock guards the same path first.
    """
    path = lock_path(config)
    with _transaction_locks_guard:
        thread_lock = _transaction_locks.setdefault(path, threading.Lock())
    with thread_lock:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            yield


@dataclass(slots=True)
class Transaction:
    """One operation's read-modify-write of the whole manifest, under the lock.

    `entries` is the live working set: callers read it to decide and mutate
    it through `put` and `forget`.  Every mutation an operation makes lands
    in one write at exit, so a multi-page release is recorded whole or not
    at all, and a crash mid-operation cannot leave half its pages recorded.

    An exception leaving the block discards every mutation, including any
    orphan adoption or recovery the open performed -- the manifest then
    still describes the state the operation started from.
    """

    config: Config
    read: Read
    entries: dict[str, Entry]
    dirty: bool = False
    recovery: Recovery | None = None

    def put(self, tool: str, entry: Entry) -> None:
        """Record `entry` as `tool`'s, replacing any entry it already had."""
        self.entries[tool] = entry
        self.dirty = True

    def forget(self, tool: str) -> None:
        """Drop `tool`'s entry. A no-op if it was never recorded."""
        if self.entries.pop(tool, None) is not None:
            self.dirty = True


@contextmanager
def transaction(config: Config | None = None) -> Iterator[Transaction]:
    """Open the manifest for one operation: load once, mutate, write once.

    The lock is held for the whole block, so the block is the commit phase
    and nothing slow belongs in it (ADR-0043).  Generation -- synthesis,
    pandoc, crawling -- touches nothing the manifest owns and must stay
    outside, or parallel installs in other processes stall on model calls.
    """
    cfg = config or Config()
    with _exclusive(cfg):
        current = read(cfg)
        recovery: Recovery | None = None
        if current.health is Health.INTACT:
            # A sound scan is the second half of the promotion test: rows
            # that parse but name pages that are gone are not a good copy.
            if Link.BROKEN not in current.links.values():
                promote(current, cfg)
            entries = dict(current.entries)
        else:
            entries, recovery = _recover(current, cfg)
            _report_recovery(recovery, cfg)
        adopted = _adopt_orphans(entries, cfg)
        if adopted:
            logger.warning("Adopted unrecorded manpath links", tools=list(adopted))
        txn = Transaction(
            config=cfg,
            read=current,
            entries=entries,
            dirty=recovery is not None or bool(adopted),
            recovery=recovery,
        )
        yield txn
        if txn.dirty:
            save(txn.entries, cfg)


@contextmanager
def joined(
    existing: Transaction | None, config: Config | None = None
) -> Iterator[Transaction]:
    """Yield the caller's open transaction, or open one for the block.

    An operation spanning several recorded pages opens one transaction and
    passes it down, so the pages land in a single write (ADR-0044).  Opening
    a nested one instead would deadlock: `flock` and the process-local lock
    both block the second acquisition against the first.
    """
    if existing is not None:
        yield existing
        return
    with transaction(config) as txn:
        yield txn
