import gzip
import json
from pathlib import Path

from typer.testing import CliRunner

from maniac import classification
from maniac.classification import ManpageFacts, collect_facts
from maniac.installer import PROVENANCE_SIGNATURE
from maniac.models import RepoSource
from maniac.sources.manpages import (
    Generator,
    HelpDerivedManpage,
    count_tp_entries,
    count_words,
    extract_sections,
)

runner = CliRunner()

_LS_LIKE_CONTENT = """\
.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.48.5.
.TH LS "1" "January 2026" "GNU coreutils 9.4" "User Commands"
.SH NAME
ls \\- list directory contents
.SH DESCRIPTION
.PP
List information about the FILEs (the current directory by default).
.PP
Sort entries alphabetically if none of the sort options is specified.
.TP
\\fB\\-a\\fR, \\fB\\-\\-all\\fR
do not ignore entries starting with .
"""


def _page(tmp_path: Path, name: str = "ls.1", content: str = _LS_LIKE_CONTENT) -> Path:
    path = tmp_path / name
    path.write_text(content, encoding="utf-8")
    return path


def test_collect_facts_classifies_a_new_page(monkeypatch, tmp_path: Path) -> None:
    page_path = _page(tmp_path)
    monkeypatch.setattr(
        classification,
        "find_installed_manpages",
        lambda manpath_bin: [HelpDerivedManpage("ls", "1", page_path)],
    )
    source = RepoSource(name="ls", target="coreutils/coreutils", is_local=False)
    monkeypatch.setattr(
        classification, "discover_candidate_source", lambda name: source
    )

    facts = collect_facts(cache_path=tmp_path / "cache.json")

    assert facts == [
        ManpageFacts(
            tool="ls",
            section="1",
            path=page_path,
            exists=True,
            is_maniac_authored=False,
            generator=Generator.HELP2MAN,
            word_count=count_words(_LS_LIKE_CONTENT),
            tp_count=count_tp_entries(_LS_LIKE_CONTENT),
            sections=extract_sections(_LS_LIKE_CONTENT),
            has_examples_section=False,
            sources=[source],
        )
    ]


def test_collect_facts_marks_maniac_authored_pages(monkeypatch, tmp_path: Path) -> None:
    content = f'{PROVENANCE_SIGNATURE}\n.\\" Tool: ls | Date: 2026-01-01\n.TH LS 1\n'
    page_path = _page(tmp_path, content=content)
    monkeypatch.setattr(
        classification,
        "find_installed_manpages",
        lambda manpath_bin: [HelpDerivedManpage("ls", "1", page_path)],
    )
    monkeypatch.setattr(classification, "discover_candidate_source", lambda name: None)

    facts = collect_facts(cache_path=tmp_path / "cache.json")

    assert facts[0].is_maniac_authored is True
    assert facts[0].generator is None
    assert facts[0].sources == []


def test_collect_facts_reuses_cache_when_key_is_unchanged(
    monkeypatch, tmp_path: Path
) -> None:
    page_path = _page(tmp_path)
    monkeypatch.setattr(
        classification,
        "find_installed_manpages",
        lambda manpath_bin: [HelpDerivedManpage("ls", "1", page_path)],
    )
    monkeypatch.setattr(classification, "discover_candidate_source", lambda name: None)
    cache_path = tmp_path / "cache.json"

    collect_facts(cache_path=cache_path)

    calls: list[Path] = []
    original = classification._classify_page

    def tracking_classify(page: HelpDerivedManpage) -> ManpageFacts:
        calls.append(page.path)
        return original(page)

    monkeypatch.setattr(classification, "_classify_page", tracking_classify)

    facts = collect_facts(cache_path=cache_path)

    assert calls == []
    assert facts[0].generator is Generator.HELP2MAN


def test_collect_facts_recomputes_when_the_page_changes(
    monkeypatch, tmp_path: Path
) -> None:
    page_path = _page(tmp_path, content=".TH LS 1\n")
    monkeypatch.setattr(
        classification,
        "find_installed_manpages",
        lambda manpath_bin: [HelpDerivedManpage("ls", "1", page_path)],
    )
    monkeypatch.setattr(classification, "discover_candidate_source", lambda name: None)
    cache_path = tmp_path / "cache.json"

    first = collect_facts(cache_path=cache_path)
    assert first[0].word_count == count_words(".TH LS 1\n")

    page_path.write_text(_LS_LIKE_CONTENT, encoding="utf-8")
    second = collect_facts(cache_path=cache_path)

    assert second[0].word_count == count_words(_LS_LIKE_CONTENT)


def test_collect_facts_drops_rows_no_longer_found_in_the_scan(
    monkeypatch, tmp_path: Path
) -> None:
    page_path = _page(tmp_path)
    monkeypatch.setattr(
        classification,
        "find_installed_manpages",
        lambda manpath_bin: [HelpDerivedManpage("ls", "1", page_path)],
    )
    monkeypatch.setattr(classification, "discover_candidate_source", lambda name: None)
    cache_path = tmp_path / "cache.json"
    collect_facts(cache_path=cache_path)

    monkeypatch.setattr(
        classification, "find_installed_manpages", lambda manpath_bin: []
    )
    collect_facts(cache_path=cache_path)

    assert json.loads(cache_path.read_text(encoding="utf-8")) == {}


def test_cache_is_json_keyed_on_path_mtime_and_size(
    monkeypatch, tmp_path: Path
) -> None:
    page_path = _page(tmp_path)
    monkeypatch.setattr(
        classification,
        "find_installed_manpages",
        lambda manpath_bin: [HelpDerivedManpage("ls", "1", page_path)],
    )
    monkeypatch.setattr(classification, "discover_candidate_source", lambda name: None)
    cache_path = tmp_path / "cache.json"

    collect_facts(cache_path=cache_path)

    stat = page_path.stat()
    raw = json.loads(cache_path.read_text(encoding="utf-8"))
    entry = raw[str(page_path)]
    assert entry["key"] == [stat.st_mtime, stat.st_size]
    assert entry["facts"]["generator"] == "help2man"
    assert entry["facts"]["sections"] == ["NAME", "DESCRIPTION"]


def test_collect_facts_skips_a_compressed_page(monkeypatch, tmp_path: Path) -> None:
    page_path = tmp_path / "ls.1.gz"
    with gzip.open(page_path, "wt", encoding="utf-8") as file:
        file.write(_LS_LIKE_CONTENT)
    monkeypatch.setattr(
        classification,
        "find_installed_manpages",
        lambda manpath_bin: [HelpDerivedManpage("ls", "1", page_path)],
    )
    monkeypatch.setattr(classification, "discover_candidate_source", lambda name: None)

    facts = collect_facts(cache_path=tmp_path / "cache.json")

    assert facts[0].generator is Generator.HELP2MAN
    assert facts[0].word_count == count_words(_LS_LIKE_CONTENT)


def test_dump_prints_one_row_per_tool_with_every_fact(monkeypatch) -> None:
    facts = [
        ManpageFacts(
            tool="ls",
            section="1",
            path=Path("/usr/share/man/man1/ls.1.gz"),
            exists=True,
            is_maniac_authored=False,
            generator=Generator.HELP2MAN,
            word_count=178,
            tp_count=63,
            sections=["NAME", "SYNOPSIS", "DESCRIPTION"],
            has_examples_section=False,
            sources=[
                RepoSource(name="ls", target="coreutils/coreutils", is_local=False)
            ],
        ),
        ManpageFacts(
            tool="gum",
            section="1",
            path=Path("/opt/gum/gum.1"),
            exists=True,
            is_maniac_authored=False,
            generator=None,
            word_count=4,
            tp_count=986,
            sections=["NAME", "DESCRIPTION"],
            has_examples_section=False,
            sources=[],
        ),
    ]
    monkeypatch.setattr(classification, "collect_facts", lambda manpath_bin: facts)

    result = runner.invoke(classification.app, [])

    assert result.exit_code == 0
    assert "ls(1)" in result.output
    assert "generator=help2man" in result.output
    assert "word_count=178" in result.output
    assert "tp_count=63" in result.output
    assert "coreutils/coreutils" in result.output
    assert "gum(1)" in result.output
    assert "generator=none" in result.output
    assert "tp_count=986" in result.output
    assert "sources=none" in result.output
