from pathlib import Path
from typing import Any

import pytest

from maniac.models import DocFile, RepoSource
from maniac.sources.docs import (
    discover_repo_manpage,
    extract_docs_from_dir,
    fetch_and_extract_docs,
    format_docs_section,
    resolve_repo_dir,
)


def test_extract_docs_from_dir(tmp_path: Path) -> None:
    # Create sample structure
    (tmp_path / "README.md").write_text("# My Tool\nSample readme", encoding="utf-8")
    (tmp_path / "USAGE.md").write_text("Usage guide", encoding="utf-8")
    (tmp_path / "CLI.md").write_text("CLI options reference", encoding="utf-8")
    (tmp_path / "random.bin").write_text("binary data", encoding="utf-8")

    docs_dir = tmp_path / "documentation"
    docs_dir.mkdir()
    (docs_dir / "guide.md").write_text("Detailed guide", encoding="utf-8")
    (docs_dir / "index.rst").write_text("Sphinx index", encoding="utf-8")

    # Ignored directory
    tests_dir = tmp_path / "tests"
    tests_dir.mkdir()
    (tests_dir / "test_doc.md").write_text("Should be ignored", encoding="utf-8")

    doc_files = extract_docs_from_dir(tmp_path)
    rel_paths = {d.rel_path for d in doc_files}

    assert "README.md" in rel_paths
    assert "USAGE.md" in rel_paths
    assert "CLI.md" in rel_paths
    assert "documentation/guide.md" in rel_paths
    assert "documentation/index.rst" in rel_paths
    assert "tests/test_doc.md" not in rel_paths


def test_extract_docs_from_dir_skips_help2man_manpages(tmp_path: Path) -> None:
    man_dir = tmp_path / "man"
    man_dir.mkdir()
    (man_dir / "tool.1").write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )

    assert extract_docs_from_dir(tmp_path) == []


def test_fetch_and_extract_docs_local(tmp_path: Path) -> None:
    (tmp_path / "README.md").write_text("# Local Project", encoding="utf-8")
    source = RepoSource(
        name="localtool",
        target=f"LOCAL:{tmp_path}",
        is_local=True,
        local_path=tmp_path,
    )

    doc_files, matched = fetch_and_extract_docs(source)
    assert len(doc_files) == 1
    assert doc_files[0].rel_path == "README.md"
    assert doc_files[0].content == "# Local Project"
    assert matched is False


def test_fetch_and_extract_docs_includes_github_wiki(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from maniac.sources import docs as docs_module

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        if clone_url.endswith(".wiki.git"):
            (dest_dir / "Home.md").write_text("# Wiki", encoding="utf-8")
        else:
            (dest_dir / "README.md").write_text("# Repo", encoding="utf-8")
        return True

    monkeypatch.setattr(docs_module, "_clone_repository", fake_clone)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    doc_files, matched = fetch_and_extract_docs(source, cache_dir=tmp_path)

    assert matched is False
    assert [(doc.rel_path, doc.content) for doc in doc_files] == [
        ("README.md", "# Repo"),
        ("wiki/Home.md", "# Wiki"),
    ]


def test_fetch_and_extract_docs_limits_repo_and_wiki_to_total_characters(
    tmp_path: Path,
) -> None:
    repo_dir = tmp_path / "tool"
    repo_dir.mkdir()
    (repo_dir / ".git").mkdir()
    (repo_dir / "README.md").write_text("12345678", encoding="utf-8")
    wiki_dir = tmp_path / "tool.wiki"
    wiki_dir.mkdir()
    (wiki_dir / ".git").mkdir()
    (wiki_dir / "Home.md").write_text("abcdefgh", encoding="utf-8")
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    doc_files, matched = fetch_and_extract_docs(
        source, cache_dir=tmp_path, max_total_chars=10
    )

    assert matched is False
    assert [doc.rel_path for doc in doc_files] == ["README.md", "wiki/Home.md"]
    assert sum(len(doc.content) for doc in doc_files) == 10


def test_format_docs_section() -> None:
    files = [
        DocFile(rel_path="README.md", content="# Tool"),
        DocFile(rel_path="docs/guide.md", content="## Guide"),
    ]
    formatted = format_docs_section(files)
    assert "### README.md" in formatted
    assert "### docs/guide.md" in formatted
    assert "# Tool" in formatted


def test_fetch_and_extract_docs_git_error(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    import subprocess

    def fake_run(*args: Any, **kwargs: Any) -> subprocess.CompletedProcess[str]:
        raise subprocess.SubprocessError("Git clone failed")

    monkeypatch.setattr(subprocess, "run", fake_run)
    source = RepoSource(
        name="remote_tool",
        target="test/remote_tool",
        is_local=False,
    )
    docs, matched = fetch_and_extract_docs(source, cache_dir=tmp_path)
    assert docs == []
    assert matched is False


def test_discover_repo_manpage_local(tmp_path: Path) -> None:
    man_dir = tmp_path / "man"
    man_dir.mkdir()
    manpage = man_dir / "tool.1"
    manpage.write_text(".TH TOOL 1\n", encoding="utf-8")
    source = RepoSource(
        name="tool", target=f"LOCAL:{tmp_path}", is_local=True, local_path=tmp_path
    )

    assert discover_repo_manpage(source, "tool") == manpage


def test_discover_repo_manpage_clones_and_reuses_cache(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from maniac.sources import docs as docs_module

    clone_calls = 0

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        nonlocal clone_calls
        clone_calls += 1
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        (dest_dir / "doc").mkdir()
        (dest_dir / "doc" / "tool.1").write_text(".TH TOOL 1\n", encoding="utf-8")
        return True

    monkeypatch.setattr(docs_module, "_clone_repository", fake_clone)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    manpage = discover_repo_manpage(source, "tool", cache_dir=tmp_path)
    assert manpage == tmp_path / "tool" / "doc" / "tool.1"

    discover_repo_manpage(source, "tool", cache_dir=tmp_path)
    assert clone_calls == 1


def test_discover_repo_manpage_no_match_returns_none(tmp_path: Path) -> None:
    source = RepoSource(
        name="tool", target=f"LOCAL:{tmp_path}", is_local=True, local_path=tmp_path
    )

    assert discover_repo_manpage(source, "tool") is None


def test_fetch_and_extract_docs_no_clone_url() -> None:
    source = RepoSource(
        name="notarget",
        target="LOCAL:/nonexistent",
        is_local=True,
        local_path=Path("/nonexistent"),
    )
    docs, matched = fetch_and_extract_docs(source)
    assert docs == []
    assert matched is False


def test_find_matching_tag_prefers_v_prefixed(monkeypatch: pytest.MonkeyPatch) -> None:
    """`gh` tags releases `v2.90.0`; a peeled annotated-tag ref (`^{}`) is stripped."""
    import subprocess

    from maniac.sources.docs import _find_matching_tag

    def fake_run(cmd: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
        assert cmd[:3] == ["git", "ls-remote", "--tags"]
        stdout = "abc\trefs/tags/v2.90.0\ndef\trefs/tags/v2.90.0^{}\n"
        return subprocess.CompletedProcess(cmd, 0, stdout=stdout, stderr="")

    monkeypatch.setattr(subprocess, "run", fake_run)
    tag = _find_matching_tag("https://github.com/cli/cli.git", "2.90.0", 10)
    assert tag == "v2.90.0"


def test_find_matching_tag_bare_version(monkeypatch: pytest.MonkeyPatch) -> None:
    """`pandoc` tags releases bare, `3.10.2` with no `v` prefix."""
    import subprocess

    from maniac.sources.docs import _find_matching_tag

    def fake_run(cmd: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            cmd, 0, stdout="abc\trefs/tags/3.10.2\n", stderr=""
        )

    monkeypatch.setattr(subprocess, "run", fake_run)
    tag = _find_matching_tag("https://github.com/jgm/pandoc.git", "3.10.2", 10)
    assert tag == "3.10.2"


def test_find_matching_tag_no_match_returns_none(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import subprocess

    from maniac.sources.docs import _find_matching_tag

    def fake_run(cmd: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            cmd, 0, stdout="abc\trefs/tags/v0.1.0\n", stderr=""
        )

    monkeypatch.setattr(subprocess, "run", fake_run)
    assert _find_matching_tag("https://github.com/owner/tool.git", "9.9.9", 10) is None


def test_resolve_repo_dir_with_version_clones_the_matching_tag(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from maniac.config import Config
    from maniac.sources import docs as docs_module

    monkeypatch.setattr(
        docs_module, "_find_matching_tag", lambda url, version, timeout: "v1.2.3"
    )
    observed_refs: list[object] = []

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        observed_refs.append(kwargs.get("ref"))
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        return True

    monkeypatch.setattr(docs_module, "_clone_repository", fake_clone)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    result = resolve_repo_dir(source, tmp_path, Config(), version="1.2.3")

    assert result == tmp_path / "tool@v1.2.3"
    assert observed_refs == ["v1.2.3"]


def test_resolve_repo_dir_with_version_no_matching_tag_returns_none(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """ADR-0016: an unmatched version is refused, not approximated from the default branch."""
    from maniac.config import Config
    from maniac.sources import docs as docs_module

    monkeypatch.setattr(
        docs_module, "_find_matching_tag", lambda url, version, timeout: None
    )
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert resolve_repo_dir(source, tmp_path, Config(), version="9.9.9") is None


def test_fetch_and_extract_docs_with_version_matched_tag(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """ADR-0019: a matching upstream tag makes the docs version-matched."""
    from maniac.sources import docs as docs_module

    monkeypatch.setattr(
        docs_module, "_find_matching_tag", lambda url, version, timeout: "v1.2.3"
    )

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        (dest_dir / "README.md").write_text("# Tagged", encoding="utf-8")
        return True

    monkeypatch.setattr(docs_module, "_clone_repository", fake_clone)
    monkeypatch.setattr(docs_module, "_fetch_github_wiki_docs", lambda *a, **kw: [])
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    doc_files, matched = fetch_and_extract_docs(
        source, cache_dir=tmp_path, version="1.2.3"
    )

    assert matched is True
    assert [d.rel_path for d in doc_files] == ["README.md"]


def test_fetch_and_extract_docs_with_version_falls_back_when_unmatched(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """ADR-0019: tier 3 falls back to the default branch on no matching tag --
    unlike tier 2's `resolve_repo_dir`, which refuses -- and reports `matched`
    False so the caller records no version rather than stamping one nobody
    checked.
    """
    from maniac.sources import docs as docs_module

    monkeypatch.setattr(
        docs_module, "_find_matching_tag", lambda url, version, timeout: None
    )

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        (dest_dir / "README.md").write_text("# Default branch", encoding="utf-8")
        return True

    monkeypatch.setattr(docs_module, "_clone_repository", fake_clone)
    monkeypatch.setattr(docs_module, "_fetch_github_wiki_docs", lambda *a, **kw: [])
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    doc_files, matched = fetch_and_extract_docs(
        source, cache_dir=tmp_path, version="9.9.9"
    )

    assert matched is False
    assert [d.rel_path for d in doc_files] == ["README.md"]


def test_discover_repo_manpage_with_version_uses_the_tagged_checkout(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from maniac.sources import docs as docs_module

    monkeypatch.setattr(
        docs_module, "_find_matching_tag", lambda url, version, timeout: "v1.2.3"
    )

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        (dest_dir / "tool.1").write_text(".TH TOOL 1\n", encoding="utf-8")
        return True

    monkeypatch.setattr(docs_module, "_clone_repository", fake_clone)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    manpage = discover_repo_manpage(source, "tool", cache_dir=tmp_path, version="1.2.3")

    assert manpage == tmp_path / "tool@v1.2.3" / "tool.1"
