from pathlib import Path
from typing import Any

import pytest

from maniac.models import DocFile, RepoSource
from maniac.sources.docs import (
    discover_repo_manpage,
    extract_docs_from_dir,
    fetch_and_extract_docs,
    format_docs_section,
)


def test_extract_docs_from_dir(tmp_path: Path) -> None:
    # Create sample structure
    (tmp_path / "README.md").write_text("# My Tool\nSample readme", encoding="utf-8")
    (tmp_path / "USAGE.md").write_text("Usage guide", encoding="utf-8")
    (tmp_path / "CLI.md").write_text("CLI options reference", encoding="utf-8")
    (tmp_path / "random.bin").write_text("binary data", encoding="utf-8")

    docs_dir = tmp_path / "documentation"
    docs_dir.mkdir()
    (docs_dir / "guide.md").write_text("Detailed guide", encoding="utf-8")
    (docs_dir / "index.rst").write_text("Sphinx index", encoding="utf-8")

    # Ignored directory
    tests_dir = tmp_path / "tests"
    tests_dir.mkdir()
    (tests_dir / "test_doc.md").write_text("Should be ignored", encoding="utf-8")

    doc_files = extract_docs_from_dir(tmp_path)
    rel_paths = {d.rel_path for d in doc_files}

    assert "README.md" in rel_paths
    assert "USAGE.md" in rel_paths
    assert "CLI.md" in rel_paths
    assert "documentation/guide.md" in rel_paths
    assert "documentation/index.rst" in rel_paths
    assert "tests/test_doc.md" not in rel_paths


def test_extract_docs_from_dir_skips_help2man_manpages(tmp_path: Path) -> None:
    man_dir = tmp_path / "man"
    man_dir.mkdir()
    (man_dir / "tool.1").write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )

    assert extract_docs_from_dir(tmp_path) == []


def test_fetch_and_extract_docs_local(tmp_path: Path) -> None:
    (tmp_path / "README.md").write_text("# Local Project", encoding="utf-8")
    source = RepoSource(
        name="localtool",
        target=f"LOCAL:{tmp_path}",
        is_local=True,
        local_path=tmp_path,
    )

    doc_files = fetch_and_extract_docs(source)
    assert len(doc_files) == 1
    assert doc_files[0].rel_path == "README.md"
    assert doc_files[0].content == "# Local Project"


def test_fetch_and_extract_docs_includes_github_wiki(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from maniac.sources import docs as docs_module

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        if clone_url.endswith(".wiki.git"):
            (dest_dir / "Home.md").write_text("# Wiki", encoding="utf-8")
        else:
            (dest_dir / "README.md").write_text("# Repo", encoding="utf-8")
        return True

    monkeypatch.setattr(docs_module, "_clone_repository", fake_clone)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    doc_files = fetch_and_extract_docs(source, cache_dir=tmp_path)

    assert [(doc.rel_path, doc.content) for doc in doc_files] == [
        ("README.md", "# Repo"),
        ("wiki/Home.md", "# Wiki"),
    ]


def test_fetch_and_extract_docs_limits_repo_and_wiki_to_total_characters(
    tmp_path: Path,
) -> None:
    repo_dir = tmp_path / "tool"
    repo_dir.mkdir()
    (repo_dir / ".git").mkdir()
    (repo_dir / "README.md").write_text("12345678", encoding="utf-8")
    wiki_dir = tmp_path / "tool.wiki"
    wiki_dir.mkdir()
    (wiki_dir / ".git").mkdir()
    (wiki_dir / "Home.md").write_text("abcdefgh", encoding="utf-8")
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    doc_files = fetch_and_extract_docs(source, cache_dir=tmp_path, max_total_chars=10)

    assert [doc.rel_path for doc in doc_files] == ["README.md", "wiki/Home.md"]
    assert sum(len(doc.content) for doc in doc_files) == 10


def test_format_docs_section() -> None:
    files = [
        DocFile(rel_path="README.md", content="# Tool"),
        DocFile(rel_path="docs/guide.md", content="## Guide"),
    ]
    formatted = format_docs_section(files)
    assert "### README.md" in formatted
    assert "### docs/guide.md" in formatted
    assert "# Tool" in formatted


def test_fetch_and_extract_docs_git_error(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    import subprocess

    def fake_run(*args: Any, **kwargs: Any) -> subprocess.CompletedProcess[str]:
        raise subprocess.SubprocessError("Git clone failed")

    monkeypatch.setattr(subprocess, "run", fake_run)
    source = RepoSource(
        name="remote_tool",
        target="test/remote_tool",
        is_local=False,
    )
    docs = fetch_and_extract_docs(source, cache_dir=tmp_path)
    assert docs == []


def test_discover_repo_manpage_local(tmp_path: Path) -> None:
    man_dir = tmp_path / "man"
    man_dir.mkdir()
    manpage = man_dir / "tool.1"
    manpage.write_text(".TH TOOL 1\n", encoding="utf-8")
    source = RepoSource(
        name="tool", target=f"LOCAL:{tmp_path}", is_local=True, local_path=tmp_path
    )

    assert discover_repo_manpage(source, "tool") == manpage


def test_discover_repo_manpage_clones_and_reuses_cache(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from maniac.sources import docs as docs_module

    clone_calls = 0

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        nonlocal clone_calls
        clone_calls += 1
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        (dest_dir / "doc").mkdir()
        (dest_dir / "doc" / "tool.1").write_text(".TH TOOL 1\n", encoding="utf-8")
        return True

    monkeypatch.setattr(docs_module, "_clone_repository", fake_clone)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    manpage = discover_repo_manpage(source, "tool", cache_dir=tmp_path)
    assert manpage == tmp_path / "tool" / "doc" / "tool.1"

    discover_repo_manpage(source, "tool", cache_dir=tmp_path)
    assert clone_calls == 1


def test_discover_repo_manpage_no_match_returns_none(tmp_path: Path) -> None:
    source = RepoSource(
        name="tool", target=f"LOCAL:{tmp_path}", is_local=True, local_path=tmp_path
    )

    assert discover_repo_manpage(source, "tool") is None


def test_fetch_and_extract_docs_no_clone_url() -> None:
    source = RepoSource(
        name="notarget",
        target="LOCAL:/nonexistent",
        is_local=True,
        local_path=Path("/nonexistent"),
    )
    docs = fetch_and_extract_docs(source)
    assert docs == []
