import gzip
from pathlib import Path

from maniac.sources import manpages
from maniac.sources.manpages import find_help_derived_manpages, is_help2man_manpage


def test_is_help2man_manpage_detects_gzip_page(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.gz"
    with gzip.open(manpage, "wt", encoding="utf-8") as file:
        file.write(
            '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n'
        )

    assert is_help2man_manpage(manpage)


def test_find_help_derived_manpages_scans_active_manpath(
    monkeypatch, tmp_path: Path
) -> None:
    manpath = tmp_path / "share" / "man"
    man1 = manpath / "man1"
    man1.mkdir(parents=True)
    generated = man1 / "generated.1"
    generated.write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )
    localized = manpath / "fr" / "man1" / "generated.1"
    localized.parent.mkdir(parents=True)
    localized.write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )
    (man1 / "help2man.1").write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )
    (man1 / "vendor.1").write_text(".TH VENDOR 1\n", encoding="utf-8")
    (man1 / "index.db").write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )
    calls: list[list[str]] = []
    scanned: list[None] = []
    totals: list[int] = []

    def fake_run(args: list[str], **kwargs: object) -> object:
        calls.append(args)
        return type("Result", (), {"returncode": 0, "stdout": str(manpath)})()

    monkeypatch.setattr(manpages.subprocess, "run", fake_run)

    assert find_help_derived_manpages(
        "/usr/bin/manpath",
        on_scan=lambda: scanned.append(None),
        on_start=totals.append,
    ) == [
        manpages.HelpDerivedManpage("generated", "1", generated),
        manpages.HelpDerivedManpage("help2man", "1", man1 / "help2man.1"),
    ]
    assert calls == [["/usr/bin/manpath"]]
    assert len(scanned) == 5
    assert totals == [5]
