import gzip
from pathlib import Path

import zstandard

from maniac.sources import manpages
from maniac.sources.manpages import (
    find_install_root_manpages,
    find_installed_manpage_path,
    find_repo_manpage,
    is_help2man_manpage,
    manpage_documents,
    read_manpage_source,
    select_primary_manpage,
)


def test_is_help2man_manpage_detects_gzip_page(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.gz"
    with gzip.open(manpage, "wt", encoding="utf-8") as file:
        file.write(
            '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n'
        )

    assert is_help2man_manpage(manpage)


def test_is_help2man_manpage_detects_zstd_page(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.zst"
    with zstandard.open(manpage, "wt", encoding="utf-8") as file:
        file.write(
            '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n'
        )

    assert is_help2man_manpage(manpage)


def test_find_repo_manpage_matches_bin_dash_pattern_in_man_dir(tmp_path: Path) -> None:
    man_dir = tmp_path / "man"
    man_dir.mkdir()
    manpage = man_dir / "tool-sub.1"
    manpage.write_text(".TH TOOL-SUB 1\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "tool") == manpage


def test_find_repo_manpage_matches_at_repo_root(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.6"
    manpage.write_text(".TH TOOL 6\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "tool") == manpage


def test_find_repo_manpage_matches_compressed_page(tmp_path: Path) -> None:
    doc_dir = tmp_path / "doc"
    doc_dir.mkdir()
    manpage = doc_dir / "pandoc.1.gz"
    with gzip.open(manpage, "wt", encoding="utf-8") as file:
        file.write(".TH PANDOC 1\n")

    assert find_repo_manpage(tmp_path, "pandoc") == manpage


def test_find_repo_manpage_reaches_share_man(tmp_path: Path) -> None:
    man1_dir = tmp_path / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    manpage = man1_dir / "tool.1"
    manpage.write_text(".TH TOOL 1\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "tool") == manpage


def test_find_repo_manpage_skips_help2man_generated_pages(tmp_path: Path) -> None:
    doc_dir = tmp_path / "doc"
    doc_dir.mkdir()
    (doc_dir / "tool.1").write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )

    assert find_repo_manpage(tmp_path, "tool") is None


def test_find_repo_manpage_ignores_unrelated_trees(tmp_path: Path) -> None:
    vendor_dir = tmp_path / "vendor" / "man"
    vendor_dir.mkdir(parents=True)
    (vendor_dir / "tool.1").write_text(".TH TOOL 1\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "tool") is None


def test_find_repo_manpage_no_match_returns_none(tmp_path: Path) -> None:
    assert find_repo_manpage(tmp_path, "tool") is None


def test_find_repo_manpage_prefers_exact_name_over_subcommand_variant(
    tmp_path: Path,
) -> None:
    man_dir = tmp_path / "man" / "man1"
    man_dir.mkdir(parents=True)
    exact = man_dir / "fzf.1"
    exact.write_text(".TH FZF 1\n", encoding="utf-8")
    (man_dir / "fzf-tmux.1").write_text(".TH FZF-TMUX 1\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "fzf") == exact


def test_find_install_root_manpages_returns_sibling_pages(tmp_path: Path) -> None:
    """The pandoc case: one package root, three binaries' pages side by side."""
    man1_dir = tmp_path / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    pages = []
    for name in ("pandoc.1.gz", "pandoc-lua.1.gz", "pandoc-server.1.gz"):
        page = man1_dir / name
        with gzip.open(page, "wt", encoding="utf-8") as file:
            file.write(".TH PANDOC 1\n")
        pages.append(page)

    assert find_install_root_manpages(tmp_path, "pandoc") == sorted(pages)


def test_find_install_root_manpages_keeps_help2man_generated_pages(
    tmp_path: Path,
) -> None:
    """Unlike `find_repo_manpage`, no generator filter: tier 1 is authoritative
    by construction (ADR-0016), not by quality (deferred past tier 1)."""
    manpage = tmp_path / "tool.1"
    manpage.write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )

    assert find_install_root_manpages(tmp_path, "tool") == [manpage]


def test_find_install_root_manpages_ignores_backup_copies(tmp_path: Path) -> None:
    """mise leaves numbered backups (`fzf.1.1`, `fzf.1.12`, ...) next to a
    reinstalled tool's page; fnmatch's fixed-width `[1-9]` class does not
    match their extra `.N` suffix."""
    exact = tmp_path / "fzf.1"
    exact.write_text(".TH FZF 1\n", encoding="utf-8")
    (tmp_path / "fzf.1.1").write_text(".TH FZF 1\n", encoding="utf-8")
    (tmp_path / "fzf.1.12").write_text(".TH FZF 1\n", encoding="utf-8")

    assert find_install_root_manpages(tmp_path, "fzf") == [exact]


def test_find_install_root_manpages_no_match_returns_empty(tmp_path: Path) -> None:
    assert find_install_root_manpages(tmp_path, "tool") == []


def test_find_install_root_manpages_reaches_one_release_wrapper_dir(
    tmp_path: Path,
) -> None:
    """The `gh`/`pastel` case: mise keeps a release tarball's own top-level
    folder (`gh_2.90.0_linux_amd64/`) between the install root and
    `share/man/man1/`, one level deeper than `find_repo_manpage` reaches."""
    man1_dir = tmp_path / "gh_2.90.0_linux_amd64" / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    exact = man1_dir / "gh.1"
    exact.write_text(".TH GH 1\n", encoding="utf-8")
    sub = man1_dir / "gh-issue-list.1"
    sub.write_text(".TH GH-ISSUE-LIST 1\n", encoding="utf-8")

    assert find_install_root_manpages(tmp_path, "gh") == sorted([exact, sub])


def test_find_install_root_manpages_does_not_reach_two_wrapper_levels(
    tmp_path: Path,
) -> None:
    """The tolerance is one wrapper level, not unbounded depth."""
    man1_dir = tmp_path / "release" / "extra" / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    (man1_dir / "tool.1").write_text(".TH TOOL 1\n", encoding="utf-8")

    assert find_install_root_manpages(tmp_path, "tool") == []


def test_find_install_root_manpages_prunes_irrelevant_trees(
    tmp_path: Path, monkeypatch
) -> None:
    """A large irrelevant tree (a venv's `lib/site-packages/`, say) must not
    be descended into once its wrapper-tolerant top level rules it out --
    the regression this fixes: an unpruned walk would visit every nested
    directory below `lib/` just to find nothing there."""
    nested = tmp_path / "lib" / "site-packages"
    for index in range(50):
        nested = nested / f"pkg{index}"
    nested.mkdir(parents=True)
    (nested / "module.py").write_text("", encoding="utf-8")

    man1_dir = tmp_path / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    manpage = man1_dir / "tool.1"
    manpage.write_text(".TH TOOL 1\n", encoding="utf-8")

    visited: list[Path] = []
    real_walk = manpages.os.walk

    def counting_walk(top, *args, **kwargs):
        for entry in real_walk(top, *args, **kwargs):
            visited.append(Path(entry[0]))
            yield entry

    monkeypatch.setattr(manpages.os, "walk", counting_walk)

    assert find_install_root_manpages(tmp_path, "tool") == [manpage]
    assert all("site-packages" not in path.parts for path in visited)
    # Bounded by the real tree (root, lib, share, share/man, share/man/man1),
    # not by the 50-level irrelevant tree below `lib/site-packages/`.
    assert len(visited) < 10


def test_find_installed_manpage_path_returns_first_hit(
    monkeypatch, tmp_path: Path
) -> None:
    target = tmp_path / "tool.1.gz"

    def fake_run(args: list[str], **kwargs: object) -> object:
        assert args == ["/usr/bin/man", "-w", "tool"]
        return type("Result", (), {"returncode": 0, "stdout": f"{target}\n"})()

    monkeypatch.setattr(manpages.subprocess, "run", fake_run)
    assert find_installed_manpage_path("/usr/bin/man", "tool") == target


def test_find_installed_manpage_path_missing_returns_none(monkeypatch) -> None:
    def fake_run(args: list[str], **kwargs: object) -> object:
        return type("Result", (), {"returncode": 1, "stdout": ""})()

    monkeypatch.setattr(manpages.subprocess, "run", fake_run)
    assert find_installed_manpage_path("/usr/bin/man", "nonexistent") is None


def test_read_manpage_source_decompresses_gzip(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.gz"
    content = ".TH TOOL 1\n.SH NAME\ntool \\- demo\n"
    with gzip.open(manpage, "wt", encoding="utf-8") as file:
        file.write(content)

    assert read_manpage_source(manpage) == content


def test_read_manpage_source_decompresses_zstd(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.zst"
    content = ".TH TOOL 1\n.SH NAME\ntool \\- demo\n"
    with zstandard.open(manpage, "wt", encoding="utf-8") as file:
        file.write(content)

    assert read_manpage_source(manpage) == content


def test_read_manpage_source_reads_plain_file(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1"
    content = ".TH TOOL 1\n"
    manpage.write_text(content, encoding="utf-8")

    assert read_manpage_source(manpage) == content


def test_select_primary_manpage_prefers_exact_over_subcommand() -> None:
    """`pandoc.1.gz`'s own package, not one of its sibling binaries' pages."""
    exact = Path("pandoc.1.gz")
    sibling = Path("pandoc-lua.1.gz")

    assert select_primary_manpage([sibling, exact], "pandoc") == exact


def test_select_primary_manpage_no_match_returns_none() -> None:
    assert select_primary_manpage([Path("pandoc-lua.1.gz")], "somethingelse") is None


def test_manpage_documents_matches_th_title() -> None:
    content = '.TH PANDOC "1" "January 2024" "pandoc 3.1.2" "User Commands"\n'
    assert manpage_documents(content, "pandoc") is True
    assert manpage_documents(content, "someothertool") is False


def test_manpage_documents_matches_mdoc_title() -> None:
    content = ".Dd January 1, 2024\n.Dt TMUX 1\n.Sh NAME\n"
    assert manpage_documents(content, "tmux") is True


def test_manpage_documents_no_title_is_false() -> None:
    assert manpage_documents("no macros here\n", "pandoc") is False
