import io
import subprocess
from pathlib import Path
from typing import Any

import pytest

from maniac.config import Config
from maniac.models import DocFile, RepoSource
from maniac.sources.docs import (
    cache,
    discover_repo_manpage,
    discover_repo_manpages,
    fetch_and_extract_docs,
    pages,
    release,
    repository,
)
from maniac.sources.docs.extraction import extract_docs_from_dir, format_docs_section
from maniac.sources.docs.pages import discovered_manpage_uri
from maniac.sources.docs.repository import resolve_repo_dir
from maniac.sources.documentation import documentation_source


def _init_cached_repo(path: Path, clone_url: str) -> None:
    subprocess.run(["git", "init", "-q", str(path)], check=True)
    subprocess.run(
        ["git", "-C", str(path), "remote", "add", "origin", clone_url],
        check=True,
    )


def test_extract_docs_from_dir(tmp_path: Path) -> None:
    # Create sample structure
    (tmp_path / "README.md").write_text("# My Tool\nSample readme", encoding="utf-8")
    (tmp_path / "USAGE.md").write_text("Usage guide", encoding="utf-8")
    (tmp_path / "CLI.md").write_text("CLI options reference", encoding="utf-8")
    (tmp_path / "random.bin").write_text("binary data", encoding="utf-8")

    docs_dir = tmp_path / "documentation"
    docs_dir.mkdir()
    (docs_dir / "guide.md").write_text("Detailed guide", encoding="utf-8")
    (docs_dir / "index.rst").write_text("Sphinx index", encoding="utf-8")

    # Ignored directory
    tests_dir = tmp_path / "tests"
    tests_dir.mkdir()
    (tests_dir / "test_doc.md").write_text("Should be ignored", encoding="utf-8")

    doc_files = extract_docs_from_dir(tmp_path)
    rel_paths = {d.rel_path for d in doc_files}

    assert "README.md" in rel_paths
    assert "USAGE.md" in rel_paths
    assert "CLI.md" in rel_paths
    assert "documentation/guide.md" in rel_paths
    assert "documentation/index.rst" in rel_paths
    assert "tests/test_doc.md" not in rel_paths


def test_extract_docs_from_dir_skips_help2man_manpages(tmp_path: Path) -> None:
    man_dir = tmp_path / "man"
    man_dir.mkdir()
    (man_dir / "tool.1").write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )

    assert extract_docs_from_dir(tmp_path) == []


def test_fetch_and_extract_docs_local(tmp_path: Path) -> None:
    (tmp_path / "README.md").write_text("# Local Project", encoding="utf-8")
    source = RepoSource(
        name="localtool",
        target=f"LOCAL:{tmp_path}",
        is_local=True,
        local_path=tmp_path,
    )

    doc_files, matched = fetch_and_extract_docs(source)
    assert len(doc_files) == 1
    assert doc_files[0].rel_path == "README.md"
    assert doc_files[0].content == "# Local Project"
    assert matched is False


def test_documentation_source_redirects_only_the_exact_tmux_build_repository() -> None:
    tmux_distribution = RepoSource(
        name="tmux", target="tmux/tmux-builds", is_local=False
    )
    unrelated_distribution = RepoSource(
        name="foo", target="owner/foo-builds", is_local=False
    )

    mapping = Config().documentation_repository_overrides

    assert documentation_source(tmux_distribution, mapping) == RepoSource(
        name="tmux", target="tmux/tmux", is_local=False
    )
    assert (
        documentation_source(unrelated_distribution, mapping) is unrelated_distribution
    )


def test_fetch_and_extract_docs_includes_github_wiki(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        if clone_url.endswith(".wiki.git"):
            (dest_dir / "Home.md").write_text("# Wiki", encoding="utf-8")
        else:
            (dest_dir / "README.md").write_text("# Repo", encoding="utf-8")
        return True

    monkeypatch.setattr(repository, "_clone_repository", fake_clone)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    doc_files, matched = fetch_and_extract_docs(source, cache_dir=tmp_path)

    assert matched is False
    assert [(doc.rel_path, doc.content) for doc in doc_files] == [
        ("README.md", "# Repo"),
        ("wiki/Home.md", "# Wiki"),
    ]


def test_fetch_and_extract_docs_limits_repo_and_wiki_to_total_characters(
    tmp_path: Path,
) -> None:
    source = RepoSource(name="tool", target="owner/tool", is_local=False)
    assert source.clone_url is not None
    repo_dir = tmp_path / "tool"
    _init_cached_repo(repo_dir, source.clone_url)
    (repo_dir / "README.md").write_text("12345678", encoding="utf-8")
    wiki_dir = tmp_path / "tool.wiki"
    wiki_dir.mkdir()
    (wiki_dir / ".git").mkdir()
    (wiki_dir / "Home.md").write_text("abcdefgh", encoding="utf-8")
    doc_files, matched = fetch_and_extract_docs(
        source, cache_dir=tmp_path, max_total_chars=10
    )

    assert matched is False
    assert [doc.rel_path for doc in doc_files] == ["README.md", "wiki/Home.md"]
    assert sum(len(doc.content) for doc in doc_files) == 10


def test_format_docs_section() -> None:
    files = [
        DocFile(rel_path="README.md", content="# Tool"),
        DocFile(rel_path="docs/guide.md", content="## Guide"),
    ]
    formatted = format_docs_section(files)
    assert "### README.md" in formatted
    assert "### docs/guide.md" in formatted
    assert "# Tool" in formatted


def test_fetch_and_extract_docs_git_error(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    import subprocess

    def fake_run(*args: Any, **kwargs: Any) -> subprocess.CompletedProcess[str]:
        raise subprocess.SubprocessError("Git clone failed")

    monkeypatch.setattr(subprocess, "run", fake_run)
    source = RepoSource(
        name="remote_tool",
        target="test/remote_tool",
        is_local=False,
    )
    docs, matched = fetch_and_extract_docs(source, cache_dir=tmp_path)
    assert docs == []
    assert matched is False


def test_discover_repo_manpage_local(tmp_path: Path) -> None:
    man_dir = tmp_path / "man"
    man_dir.mkdir()
    manpage = man_dir / "tool.1"
    manpage.write_text(".TH TOOL 1\n", encoding="utf-8")
    source = RepoSource(
        name="tool", target=f"LOCAL:{tmp_path}", is_local=True, local_path=tmp_path
    )

    assert discover_repo_manpage(source, "tool") == manpage


def test_discover_repo_manpage_rejects_a_page_naming_a_different_binary(
    tmp_path: Path,
) -> None:
    man_dir = tmp_path / "man"
    man_dir.mkdir()
    (man_dir / "tool.1").write_text(".TH OTHER 1\n", encoding="utf-8")
    source = RepoSource(
        name="tool", target=f"LOCAL:{tmp_path}", is_local=True, local_path=tmp_path
    )

    assert discover_repo_manpage(source, "tool") is None


def test_discover_repo_manpage_uses_a_bare_cache_without_clone_or_checkout(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:

    calls: list[list[str]] = []
    fetched = False

    def fake_run(cmd: list[str], **kwargs: Any) -> subprocess.CompletedProcess:
        nonlocal fetched
        calls.append(cmd)
        if "rev-parse" in cmd:
            return subprocess.CompletedProcess(cmd, 0 if fetched else 1, stdout="ref\n")
        if "fetch" in cmd:
            fetched = True
            return subprocess.CompletedProcess(cmd, 0, stdout="")
        if "ls-tree" in cmd:
            return subprocess.CompletedProcess(
                cmd,
                0,
                stdout="tests/" + "x" * 300 + "/fixture\nman/tool.1\n",
            )
        if "show" in cmd:
            return subprocess.CompletedProcess(cmd, 0, stdout=b".TH TOOL 1\n")
        if "remote" in cmd and "get-url" in cmd:
            return subprocess.CompletedProcess(
                cmd, 0, stdout="https://github.com/owner/tool.git\n"
            )
        return subprocess.CompletedProcess(cmd, 0, stdout="")

    monkeypatch.setattr(subprocess, "run", fake_run)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    manpage = discover_repo_manpage(source, "tool", cache_dir=tmp_path)
    assert manpage is not None
    assert manpage.read_text(encoding="utf-8") == ".TH TOOL 1\n"
    assert discovered_manpage_uri(manpage) == (
        "https://github.com/owner/tool/blob/HEAD/man/tool.1"
    )
    discover_repo_manpage(source, "tool", cache_dir=tmp_path)
    assert not any(command[1] in {"clone", "checkout"} for command in calls)
    assert sum("fetch" in command for command in calls) == 1
    assert not any(len(path.name) > 255 for path in tmp_path.rglob("*"))


def test_discover_repo_manpage_no_match_returns_none(tmp_path: Path) -> None:
    source = RepoSource(
        name="tool", target=f"LOCAL:{tmp_path}", is_local=True, local_path=tmp_path
    )

    assert discover_repo_manpage(source, "tool") is None


def test_fetch_and_extract_docs_no_clone_url() -> None:
    source = RepoSource(
        name="notarget",
        target="LOCAL:/nonexistent",
        is_local=True,
        local_path=Path("/nonexistent"),
    )
    docs, matched = fetch_and_extract_docs(source)
    assert docs == []
    assert matched is False


def test_find_matching_tag_prefers_v_prefixed(monkeypatch: pytest.MonkeyPatch) -> None:
    """`gh` tags releases `v2.90.0`; a peeled annotated-tag ref (`^{}`) is stripped."""
    import subprocess

    from maniac.sources.docs.repository import _find_matching_tag

    def fake_run(cmd: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
        assert cmd[:3] == ["git", "ls-remote", "--tags"]
        stdout = "abc\trefs/tags/v2.90.0\ndef\trefs/tags/v2.90.0^{}\n"
        return subprocess.CompletedProcess(cmd, 0, stdout=stdout, stderr="")

    monkeypatch.setattr(subprocess, "run", fake_run)
    tag = _find_matching_tag("https://github.com/cli/cli.git", "2.90.0", 10)
    assert tag == "v2.90.0"


def test_find_matching_tag_bare_version(monkeypatch: pytest.MonkeyPatch) -> None:
    """`pandoc` tags releases bare, `3.10.2` with no `v` prefix."""
    import subprocess

    from maniac.sources.docs.repository import _find_matching_tag

    def fake_run(cmd: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            cmd, 0, stdout="abc\trefs/tags/3.10.2\n", stderr=""
        )

    monkeypatch.setattr(subprocess, "run", fake_run)
    tag = _find_matching_tag("https://github.com/jgm/pandoc.git", "3.10.2", 10)
    assert tag == "3.10.2"


def test_find_matching_tag_no_match_returns_none(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import subprocess

    from maniac.sources.docs.repository import _find_matching_tag

    def fake_run(cmd: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
        return subprocess.CompletedProcess(
            cmd, 0, stdout="abc\trefs/tags/v0.1.0\n", stderr=""
        )

    monkeypatch.setattr(subprocess, "run", fake_run)
    assert _find_matching_tag("https://github.com/owner/tool.git", "9.9.9", 10) is None


def test_discovery_resolves_a_tag_once_before_tree_and_release_probes(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    lookups = 0

    def find_tag(*args: object) -> str:
        nonlocal lookups
        lookups += 1
        return "v1.2.3"

    monkeypatch.setattr(repository, "_find_matching_tag", find_tag)
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pages._ProbeResult([], True),
    )
    monkeypatch.setattr(
        release,
        "_discover_github_release_manpages_result",
        lambda *args: pages._ProbeResult([], True),
    )
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert lookups == 1


def test_versioned_probe_cache_skips_network_for_positive_and_negative_results(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    source = RepoSource(name="tool", target="owner/tool", is_local=False)
    page = tmp_path / "manpages" / "key" / "tool.1"
    page.parent.mkdir(parents=True)
    page.write_text(".TH TOOL 1\n", encoding="utf-8")
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.2.3")
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pages._ProbeResult([page], True),
    )
    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == [page]

    monkeypatch.setattr(
        repository, "_find_matching_tag", lambda *args: pytest.fail("network used")
    )
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pytest.fail("network used"),
    )
    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == [page]

    missing = RepoSource(name="missing", target="owner/missing", is_local=False)
    monkeypatch.setattr(
        repository,
        "_find_matching_tag_cached_result",
        lambda *args: (None, True),
    )
    assert discover_repo_manpages(missing, "missing", tmp_path, version="1.2.3") == []
    monkeypatch.setattr(
        repository,
        "_find_matching_tag_cached_result",
        lambda *args: pytest.fail("network used"),
    )
    assert discover_repo_manpages(missing, "missing", tmp_path, version="1.2.3") == []


def test_definitive_versioned_probe_miss_skips_tree_and_release_on_second_call(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    source = RepoSource(name="tool", target="owner/tool", is_local=False)
    tree_calls = 0
    release_calls = 0

    def tree(*args: object) -> object:
        nonlocal tree_calls
        tree_calls += 1
        return pages._ProbeResult([], True)

    def release_probe(*args: object) -> object:
        nonlocal release_calls
        release_calls += 1
        return pages._ProbeResult([], True)

    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.2.3")
    monkeypatch.setattr(repository, "_discover_remote_manpage_result", tree)
    monkeypatch.setattr(
        release, "_discover_github_release_manpages_result", release_probe
    )

    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert (tree_calls, release_calls) == (1, 1)

    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pytest.fail("tree used"),
    )
    monkeypatch.setattr(
        release,
        "_discover_github_release_manpages_result",
        lambda *args: pytest.fail("release used"),
    )
    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []


def test_expired_definitive_probe_miss_refreshes(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    now = 1000.0
    calls = 0

    def tree(*args: object) -> object:
        nonlocal calls
        calls += 1
        return pages._ProbeResult([], True)

    monkeypatch.setattr(cache.time, "time", lambda: now)
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.2.3")
    monkeypatch.setattr(repository, "_discover_remote_manpage_result", tree)
    monkeypatch.setattr(
        release,
        "_discover_github_release_manpages_result",
        lambda *args: pages._ProbeResult([], True),
    )
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    now += cache._NEGATIVE_CACHE_TTL + 1
    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert calls == 2


def test_release_metadata_revalidates_after_a_definitive_probe_miss_expires(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    now = 1000.0
    metadata_calls = 0

    def download(url: str, cfg: object) -> bytes:
        nonlocal metadata_calls
        if url.startswith("https://api.github.com/"):
            metadata_calls += 1
            if metadata_calls == 1:
                return b'{"assets": []}'
            return (
                b'{"assets": [{"name": "tool.1", '
                b'"browser_download_url": "https://example.test/tool.1"}]}'
            )
        return b".TH TOOL 1\n"

    monkeypatch.setattr(cache.time, "time", lambda: now)
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.2.3")
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pages._ProbeResult([], True),
    )
    monkeypatch.setattr(cache, "_download", download)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    now += cache._NEGATIVE_CACHE_TTL - 1
    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert metadata_calls == 1

    now += 2
    found = discover_repo_manpages(source, "tool", tmp_path, version="1.2.3")

    assert [page.name for page in found] == ["tool.1"]
    assert metadata_calls == 2


def test_transient_probe_failure_is_not_cached(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    tree_calls = 0

    def tree(*args: object) -> object:
        nonlocal tree_calls
        tree_calls += 1
        return pages._ProbeResult([], False)

    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.2.3")
    monkeypatch.setattr(repository, "_discover_remote_manpage_result", tree)
    monkeypatch.setattr(
        release,
        "_discover_github_release_manpages_result",
        lambda *args: pages._ProbeResult([], False),
    )
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert tree_calls == 2


def test_tree_failure_does_not_cache_a_definitive_release_miss(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    tree_calls = 0
    release_calls = 0

    def tree(*args: object) -> object:
        nonlocal tree_calls
        tree_calls += 1
        return pages._ProbeResult([], False)

    def release_probe(*args: object) -> object:
        nonlocal release_calls
        release_calls += 1
        return pages._ProbeResult([], True)

    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.2.3")
    monkeypatch.setattr(repository, "_discover_remote_manpage_result", tree)
    monkeypatch.setattr(
        release, "_discover_github_release_manpages_result", release_probe
    )
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert (tree_calls, release_calls) == (2, 2)


@pytest.mark.parametrize("status", [404, 410])
def test_github_release_not_found_is_a_definitive_probe_miss(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, status: int
) -> None:
    from email.message import Message
    from urllib.error import HTTPError

    calls = 0

    def missing(*args: object, **kwargs: object) -> object:
        nonlocal calls
        calls += 1
        raise HTTPError(
            "https://api.github.com/release", status, "missing", Message(), None
        )

    monkeypatch.setattr(cache, "_open", missing)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)
    cfg = Config(cache_dir=tmp_path)

    result = release._discover_github_release_manpages_result(
        pages._Probe(source, "tool", tmp_path, cfg, "1.2.3", "v1.2.3")
    )

    assert result == pages._ProbeResult([], True)
    assert calls == 1


def test_malformed_release_metadata_does_not_cache_the_probe(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    tree_calls = 0

    def tree(*args: object) -> object:
        nonlocal tree_calls
        tree_calls += 1
        return pages._ProbeResult([], True)

    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.2.3")
    monkeypatch.setattr(repository, "_discover_remote_manpage_result", tree)
    monkeypatch.setattr(cache, "_download", lambda *args: b"[]")
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert tree_calls == 2


def test_concurrent_definitive_probe_misses_are_single_flight(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from concurrent.futures import ThreadPoolExecutor
    from threading import Event, Lock

    calls = 0
    calls_lock = Lock()
    tree_started = Event()
    release_tree = Event()

    def tree(*args: object) -> object:
        nonlocal calls
        with calls_lock:
            calls += 1
        tree_started.set()
        assert release_tree.wait(timeout=2)
        return pages._ProbeResult([], True)

    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.2.3")
    monkeypatch.setattr(repository, "_discover_remote_manpage_result", tree)
    monkeypatch.setattr(
        release,
        "_discover_github_release_manpages_result",
        lambda *args: pages._ProbeResult([], True),
    )
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    with ThreadPoolExecutor(max_workers=4) as executor:
        first = executor.submit(
            discover_repo_manpages, source, "tool", tmp_path, None, "1.2.3"
        )
        assert tree_started.wait(timeout=2)
        rest = [
            executor.submit(
                discover_repo_manpages, source, "tool", tmp_path, None, "1.2.3"
            )
            for _ in range(3)
        ]
        release_tree.set()
        assert first.result() == []
        assert [future.result() for future in rest] == [[], [], []]

    assert calls == 1


def test_concurrent_binaries_share_tag_and_release_metadata(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from concurrent.futures import ThreadPoolExecutor

    tag_lookups = 0
    downloads = 0

    def find_tag(*args: object) -> str:
        nonlocal tag_lookups
        tag_lookups += 1
        return "v1.2.3"

    def download(*args: object) -> bytes:
        nonlocal downloads
        downloads += 1
        return b'{"assets": []}'

    monkeypatch.setattr(repository, "_find_matching_tag", find_tag)
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pages._ProbeResult([], True),
    )
    monkeypatch.setattr(cache, "_download", download)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    with ThreadPoolExecutor(max_workers=4) as executor:
        results = list(
            executor.map(
                lambda binary: discover_repo_manpages(
                    source, binary, tmp_path, version="1.2.3"
                ),
                ["tool", "tool-a", "tool-b", "tool-c"],
            )
        )

    assert results == [[], [], [], []]
    assert tag_lookups == 1
    assert downloads == 1


def test_expired_negative_tag_cache_refreshes(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    now = 1000.0
    lookups = 0

    def fake_time() -> float:
        return now

    def find_tag(*args: object) -> None:
        nonlocal lookups
        lookups += 1

    monkeypatch.setattr(cache.time, "time", fake_time)
    monkeypatch.setattr(repository, "_find_matching_tag", find_tag)
    cfg = Config(cache_dir=tmp_path)
    assert repository._find_matching_tag_cached(tmp_path, "url", "1.2.3", cfg) is None
    now += cache._NEGATIVE_CACHE_TTL + 1
    assert repository._find_matching_tag_cached(tmp_path, "url", "1.2.3", cfg) is None
    assert lookups == 2


def test_transient_tag_lookup_is_not_cached(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    calls = 0

    def fail(*args: object, **kwargs: object) -> object:
        nonlocal calls
        calls += 1
        raise subprocess.TimeoutExpired("git", 1)

    monkeypatch.setattr(repository.subprocess, "run", fail)
    cfg = Config(cache_dir=tmp_path)
    assert repository._find_matching_tag_cached(tmp_path, "url", "1.2.3", cfg) is None
    assert repository._find_matching_tag_cached(tmp_path, "url", "1.2.3", cfg) is None
    assert calls == 2


def test_nonzero_tag_lookup_is_not_cached(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    calls = 0

    def fail(cmd: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        nonlocal calls
        calls += 1
        return subprocess.CompletedProcess(cmd, 128, stdout="", stderr="offline")

    monkeypatch.setattr(repository.subprocess, "run", fail)
    cfg = Config(cache_dir=tmp_path)
    assert repository._find_matching_tag_cached(tmp_path, "url", "1.2.3", cfg) is None
    assert repository._find_matching_tag_cached(tmp_path, "url", "1.2.3", cfg) is None
    assert calls == 2


@pytest.mark.parametrize("status", [404, 410])
def test_definitively_missing_download_is_cached(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, status: int
) -> None:
    from email.message import Message
    from urllib.error import HTTPError

    calls = 0

    def missing(*args: object, **kwargs: object) -> object:
        nonlocal calls
        calls += 1
        raise HTTPError("https://example.test/page", status, "missing", Message(), None)

    monkeypatch.setattr(cache, "_open", missing)
    cfg = Config(cache_dir=tmp_path)
    assert (
        cache._download_cached_result("https://example.test/page", tmp_path, cfg)[0]
        is None
    )
    assert (
        cache._download_cached_result("https://example.test/page", tmp_path, cfg)[0]
        is None
    )
    assert calls == 1


@pytest.mark.parametrize("failure", ["url", "server"])
def test_transient_download_is_not_cached(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, failure: str
) -> None:
    from email.message import Message
    from urllib.error import HTTPError, URLError

    calls = 0

    def unavailable(*args: object, **kwargs: object) -> object:
        nonlocal calls
        calls += 1
        if failure == "url":
            raise URLError("offline")
        raise HTTPError(
            "https://example.test/page", 503, "unavailable", Message(), None
        )

    monkeypatch.setattr(cache, "_open", unavailable)
    cfg = Config(cache_dir=tmp_path)
    assert (
        cache._download_cached_result("https://example.test/page", tmp_path, cfg)[0]
        is None
    )
    assert (
        cache._download_cached_result("https://example.test/page", tmp_path, cfg)[0]
        is None
    )
    assert calls == 2


@pytest.mark.parametrize("status", [401, 403])
def test_auth_and_rate_limit_failures_are_not_definitive(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, status: int
) -> None:
    from email.message import Message
    from urllib.error import HTTPError

    def denied(*args: object, **kwargs: object) -> object:
        raise HTTPError(
            "https://api.github.com/release", status, "denied", Message(), None
        )

    monkeypatch.setattr(cache, "_open", denied)
    cfg = Config(cache_dir=tmp_path)

    content, definitive = cache._download_result("https://api.github.com/release", cfg)

    assert content is None
    assert definitive is False


def test_authorization_header_only_for_github_api_host(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(cache, "resolve_github_token", lambda: "stub-token")

    assert (
        cache._github_headers("https://api.github.com/repos/x/y")["Authorization"]
        == "Bearer stub-token"
    )
    assert "Authorization" not in cache._github_headers(
        "https://objects.githubusercontent.com/x"
    )
    assert "Authorization" not in cache._github_headers(
        "https://evil.example.com/api.github.com"
    )


def test_no_authorization_header_without_a_token() -> None:
    assert "Authorization" not in cache._github_headers(
        "https://api.github.com/repos/x/y"
    )


def test_redirect_handler_drops_authorization_across_hosts() -> None:
    from http.client import HTTPMessage
    from urllib.request import Request

    request = Request(
        "https://api.github.com/repos/x/y/releases/assets/1",
        headers={"Authorization": "Bearer secret", "User-Agent": "maniac"},
    )
    handler = cache._AuthStrippingRedirectHandler()

    new_request = handler.redirect_request(
        request,
        io.BytesIO(),
        302,
        "Found",
        HTTPMessage(),
        "https://objects.githubusercontent.com/x",
    )

    assert new_request is not None
    assert "Authorization" not in new_request.headers


def test_redirect_handler_keeps_authorization_same_host() -> None:
    from http.client import HTTPMessage
    from urllib.request import Request

    request = Request(
        "https://api.github.com/repos/x/y/releases/assets/1",
        headers={"Authorization": "Bearer secret", "User-Agent": "maniac"},
    )
    handler = cache._AuthStrippingRedirectHandler()

    new_request = handler.redirect_request(
        request,
        io.BytesIO(),
        302,
        "Found",
        HTTPMessage(),
        "https://api.github.com/other/path",
    )

    assert new_request is not None
    assert new_request.headers.get("Authorization") == "Bearer secret"


def test_materialize_page_replaces_an_interrupted_write(tmp_path: Path) -> None:
    source = RepoSource(name="tool", target="owner/tool", is_local=False)
    key = pages.sha256(f"{source.target}\0v1\0tool.1".encode()).hexdigest()
    destination = tmp_path / "manpages" / key / "tool.1"
    destination.parent.mkdir(parents=True)
    destination.write_bytes(b".TH TO")

    page = pages._materialize_page(tmp_path, source, "v1", "tool.1", b".TH TOOL 1\n")

    assert page == destination
    assert page.read_bytes() == b".TH TOOL 1\n"


def test_malformed_upstream_cache_is_replaced(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    source = RepoSource(name="tool", target="owner/tool", is_local=False)
    assert source.clone_url is not None
    path = cache._upstream_cache_path(
        tmp_path, "probes", "source-uri-v1", source.clone_url, "1.2.3", "tool"
    )
    path.parent.mkdir(parents=True)
    path.write_text("not json", encoding="utf-8")
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: None)

    assert discover_repo_manpages(source, "tool", tmp_path, version="1.2.3") == []
    assert not path.exists()


def test_resolve_repo_dir_with_version_clones_the_matching_tag(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from maniac.config import Config

    monkeypatch.setattr(
        repository, "_find_matching_tag", lambda url, version, timeout: "v1.2.3"
    )
    observed_refs: list[object] = []

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        observed_refs.append(kwargs.get("ref"))
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        return True

    monkeypatch.setattr(repository, "_clone_repository", fake_clone)
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    result = resolve_repo_dir(source, tmp_path, Config(), version="1.2.3")

    assert result == tmp_path / "tool@v1.2.3"
    assert observed_refs == ["v1.2.3"]


def test_resolve_repo_dir_with_version_no_matching_tag_returns_none(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """ADR-0016: an unmatched version is refused, not approximated from the default branch."""
    from maniac.config import Config

    monkeypatch.setattr(
        repository, "_find_matching_tag", lambda url, version, timeout: None
    )
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert resolve_repo_dir(source, tmp_path, Config(), version="9.9.9") is None


def test_fetch_and_extract_docs_with_version_matched_tag(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """ADR-0019: a matching upstream tag makes the docs version-matched."""
    monkeypatch.setattr(
        repository, "_find_matching_tag", lambda url, version, timeout: "v1.2.3"
    )

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        (dest_dir / "README.md").write_text("# Tagged", encoding="utf-8")
        return True

    monkeypatch.setattr(repository, "_clone_repository", fake_clone)
    monkeypatch.setattr(repository, "_fetch_github_wiki_docs", lambda *a, **kw: [])
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    doc_files, matched = fetch_and_extract_docs(
        source, cache_dir=tmp_path, version="1.2.3"
    )

    assert matched is True
    assert [d.rel_path for d in doc_files] == ["README.md"]


def test_fetch_and_extract_docs_with_version_falls_back_when_unmatched(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """ADR-0019: tier 3 falls back to the default branch on no matching tag --
    unlike tier 2's `resolve_repo_dir`, which refuses -- and reports `matched`
    False so the caller records no version rather than stamping one nobody
    checked.
    """
    monkeypatch.setattr(
        repository, "_find_matching_tag", lambda url, version, timeout: None
    )

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        (dest_dir / "README.md").write_text("# Default branch", encoding="utf-8")
        return True

    monkeypatch.setattr(repository, "_clone_repository", fake_clone)
    monkeypatch.setattr(repository, "_fetch_github_wiki_docs", lambda *a, **kw: [])
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    doc_files, matched = fetch_and_extract_docs(
        source, cache_dir=tmp_path, version="9.9.9"
    )

    assert matched is False
    assert [d.rel_path for d in doc_files] == ["README.md"]


def test_discover_repo_manpage_with_version_fetches_the_exact_tag(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        repository, "_find_matching_tag", lambda url, version, timeout: "v1.2.3"
    )

    fetched: list[list[str]] = []

    def fake_fetch(
        repo: Path, clone_url: str, ref_name: str, fetch_ref: str, cfg: object
    ) -> str:
        fetched.append([ref_name, fetch_ref])
        return "refs/maniac/tag"

    monkeypatch.setattr(repository, "_fetch_bare_ref", fake_fetch)
    monkeypatch.setattr(repository, "_git_stdout", lambda *args: "tool.1\n")
    monkeypatch.setattr(repository, "_git_bytes", lambda *args: b".TH TOOL 1\n")
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    manpage = discover_repo_manpage(source, "tool", cache_dir=tmp_path, version="1.2.3")

    assert manpage is not None
    assert fetched == [["v1.2.3", "refs/tags/v1.2.3"]]
    assert discovered_manpage_uri(manpage) == (
        "https://github.com/owner/tool/blob/v1.2.3/tool.1"
    )


def test_github_release_assets_accept_only_actual_matching_manpage(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    def archive(members: dict[str, bytes]) -> bytes:
        import io
        import tarfile

        output = io.BytesIO()
        with tarfile.open(fileobj=output, mode="w:gz") as tar:
            for name, content in members.items():
                info = tarfile.TarInfo(name)
                info.size = len(content)
                tar.addfile(info, io.BytesIO(content))
        return output.getvalue()

    def fake_download(url: str, cfg: object) -> bytes:
        if url.startswith("https://api.github.com/"):
            return b'{"assets": [{"name": "completions-0.23.5.tar.gz", "size": 5, "browser_download_url": "https://example.test/completions-0.23.5.tar.gz"}, {"name": "man-0.23.5.tar.gz", "size": 5, "browser_download_url": "https://example.test/man-0.23.5.tar.gz"}]}'
        if "completions" in url:
            return archive({"completions/eza.fish": b"complete -c eza"})
        return archive({"man/eza.1": b".TH EZA 1\n"})

    monkeypatch.setattr(cache, "_download", fake_download)
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pages._ProbeResult([], True),
    )
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v0.23.5")
    source = RepoSource(name="eza", target="eza-community/eza", is_local=False)

    page = discover_repo_manpage(source, "eza", cache_dir=tmp_path, version="0.23.5")
    assert page is not None
    assert page.read_text(encoding="utf-8") == ".TH EZA 1\n"


def test_github_release_archive_keeps_valid_companion_manpages(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    import io
    import tarfile

    output = io.BytesIO()
    with tarfile.open(fileobj=output, mode="w:gz") as tar:
        for name, content in {
            "./target/man-0.23.5/eza.1": b".TH EZA 1\n",
            "./target/man-0.23.5/eza_colors.5": b".TH EZA_COLORS 5\n",
            "./target/man-0.23.5/eza_colors-explanation.5": b".TH EZA_COLORS_EXPLANATION 5\n",
            "./target/man-0.23.5/foo.1": b".TH FOO 1\n",
            "./target/completions/eza.fish": b"complete -c eza",
            "./target/man-0.23.5/not-a-page.txt": b".TH NOT_A_PAGE 1\n",
        }.items():
            info = tarfile.TarInfo(name)
            info.size = len(content)
            tar.addfile(info, io.BytesIO(content))

    def fake_download(url: str, cfg: object) -> bytes:
        if url.startswith("https://api.github.com/"):
            return b'{"assets": [{"name": "eza-manpages.tar.gz", "size": 5, "browser_download_url": "https://example.test/eza-manpages.tar.gz"}]}'
        return output.getvalue()

    monkeypatch.setattr(cache, "_download", fake_download)
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pages._ProbeResult([], True),
    )
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v0.23.5")
    source = RepoSource(name="eza", target="eza-community/eza", is_local=False)

    found = discover_repo_manpages(source, "eza", cache_dir=tmp_path, version="0.23.5")

    assert [page.name for page in found] == [
        "eza.1",
        "eza_colors.5",
        "eza_colors-explanation.5",
    ]
    assert all(page.parent.parent.name == "manpages" for page in found)
    assert all(
        discovered_manpage_uri(page) == "https://example.test/eza-manpages.tar.gz"
        for page in found
    )


def test_release_probe_skips_large_non_man_archives(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    requested: list[str] = []

    def fake_download(url: str, cfg: object) -> bytes:
        requested.append(url)
        if url.startswith("https://api.github.com/"):
            return b'{"assets": [{"name": "eza_x86_64.tar.gz", "size": 780000, "browser_download_url": "https://example.test/linux"}, {"name": "eza.zip", "size": 1500000, "browser_download_url": "https://example.test/zip"}, {"name": "man-0.23.5.tar.gz", "size": 10500, "browser_download_url": "https://example.test/man"}]}'
        return b"not a tar archive"

    monkeypatch.setattr(cache, "_download", fake_download)
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pages._ProbeResult([], True),
    )
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v0.23.5")
    source = RepoSource(name="eza", target="eza-community/eza", is_local=False)

    assert (
        discover_repo_manpages(source, "eza", cache_dir=tmp_path, version="0.23.5")
        == []
    )
    assert requested == [
        "https://api.github.com/repos/eza-community/eza/releases/tags/v0.23.5",
        "https://example.test/man",
    ]


def test_malformed_release_asset_degrades_to_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(cache, "_download", lambda *args: b"not a tar archive")
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pages._ProbeResult([], True),
    )
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.0")
    source = RepoSource(name="tool", target="owner/tool", is_local=False)
    assert (
        discover_repo_manpage(source, "tool", cache_dir=tmp_path, version="1.0") is None
    )


def test_non_object_release_metadata_degrades_to_missing(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(cache, "_download", lambda *args: b"[]")
    monkeypatch.setattr(
        repository,
        "_discover_remote_manpage_result",
        lambda *args: pages._ProbeResult([], True),
    )
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.0")
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert (
        discover_repo_manpages(source, "tool", cache_dir=tmp_path, version="1.0") == []
    )


def test_release_archive_rejects_an_oversized_member(tmp_path: Path) -> None:
    import io
    import tarfile

    content = b".TH TOOL 1\n" + b"x" * pages._RELEASE_MEMBER_LIMIT
    output = io.BytesIO()
    with tarfile.open(fileobj=output, mode="w:gz") as tar:
        info = tarfile.TarInfo("man/tool.1")
        info.size = len(content)
        tar.addfile(info, io.BytesIO(content))
    source = RepoSource(name="tool", target="owner/tool", is_local=False)

    assert (
        release._manpages_from_release_archive(
            output.getvalue(),
            pages._Probe(source, "tool", tmp_path, Config(), None),
            "v1.0",
        )
        == []
    )


def test_compressed_manpage_expanding_past_limit_is_rejected(tmp_path: Path) -> None:
    import gzip

    page = tmp_path / "tool.1.gz"
    with gzip.open(page, "wb") as file:
        file.write(b".TH TOOL 1\n" + b"x" * pages._RELEASE_MEMBER_LIMIT)

    assert pages._valid_page(page, "tool") is False


def test_truncated_compressed_manpage_is_rejected(tmp_path: Path) -> None:
    import gzip

    page = tmp_path / "tool.1.gz"
    page.write_bytes(gzip.compress(b".TH TOOL 1\n")[:-4])

    assert pages._valid_page(page, "tool") is False


def test_download_degrades_on_invalid_request_url(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(cache, "_open", lambda *args, **kwargs: None)

    assert cache._download("\x00", Config()) is None


def test_clone_configures_sparse_checkout_for_nested_documentation(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from types import SimpleNamespace

    calls: list[list[str]] = []

    def fake_run(command: list[str], **kwargs: object) -> SimpleNamespace:
        calls.append(command)
        return SimpleNamespace(returncode=0, stderr="")

    monkeypatch.setattr(repository.subprocess, "run", fake_run)

    assert repository._clone_repository(
        "https://example.test/tool.git", tmp_path, Config()
    )
    assert calls[1][3:6] == ["sparse-checkout", "set", "--no-cone"]
    assert {"docs", "documentation", "man", "manpages"} <= set(calls[1])


@pytest.mark.parametrize("tag", ["v1.2.3", "1.2.3"])
def test_resolve_repo_dir_reuses_a_valid_versioned_cache_without_network(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, tag: str
) -> None:
    from maniac.config import Config

    cached_dir = tmp_path / f"tool@{tag}"
    source = RepoSource(name="tool", target="owner/tool", is_local=False)
    assert source.clone_url is not None
    _init_cached_repo(cached_dir, source.clone_url)

    monkeypatch.setattr(
        repository,
        "_find_matching_tag",
        lambda *args: pytest.fail("warm cache must skip ls-remote"),
    )
    monkeypatch.setattr(
        repository,
        "_clone_repository",
        lambda *args, **kwargs: pytest.fail("warm cache must skip cloning"),
    )

    assert resolve_repo_dir(source, tmp_path, Config(), version="1.2.3") == cached_dir


def test_resolve_repo_dir_discards_a_malformed_versioned_cache(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from maniac.config import Config

    malformed_dir = tmp_path / "tool@v1.2.3"
    malformed_dir.mkdir()
    (malformed_dir / "stray").write_text("not a checkout", encoding="utf-8")
    source = RepoSource(name="tool", target="owner/tool", is_local=False)
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "1.2.3")

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        assert not malformed_dir.exists()
        dest_dir.mkdir()
        (dest_dir / ".git").mkdir()
        return True

    monkeypatch.setattr(repository, "_clone_repository", fake_clone)

    assert resolve_repo_dir(source, tmp_path, Config(), version="1.2.3") == (
        tmp_path / "tool@1.2.3"
    )


def test_resolve_repo_dir_rejects_cache_from_a_different_repository(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from maniac.config import Config

    cached_dir = tmp_path / "tool@v1.2.3"
    _init_cached_repo(cached_dir, "https://github.com/old/tool.git")
    source = RepoSource(name="tool", target="new/tool", is_local=False)
    monkeypatch.setattr(repository, "_find_matching_tag", lambda *args: "v1.2.3")

    def fake_clone(
        clone_url: str, dest_dir: Path, cfg: object, **kwargs: object
    ) -> bool:
        assert not cached_dir.exists()
        _init_cached_repo(dest_dir, clone_url)
        return True

    monkeypatch.setattr(repository, "_clone_repository", fake_clone)

    assert resolve_repo_dir(source, tmp_path, Config(), version="1.2.3") == cached_dir
