import gzip
from pathlib import Path

import zstandard

from maniac.sources import manpages
from maniac.sources.manpages import (
    Dialect,
    Generator,
    count_tp_entries,
    count_words,
    detect_dialect_from_content,
    detect_generator,
    detect_generator_from_content,
    extract_sections,
    find_help_derived_manpages,
    find_install_root_manpages,
    find_installed_manpage_path,
    find_installed_manpages,
    find_repo_manpage,
    has_examples_section,
    is_help2man_manpage,
    manpage_documents,
    read_manpage_source,
    select_primary_manpage,
)

# Trimmed fixtures of the real `ls.1`/`fold.1` pages on the development
# system: both help2man-generated with 7 sections, but help2man's `--include`
# spliced extra `.PP` prose into `ls.1` and left `fold.1` terse.
_LS_LIKE = """\
.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.48.5.
.TH LS "1" "January 2026" "GNU coreutils 9.4" "User Commands"
.SH NAME
ls \\- list directory contents
.SH SYNOPSIS
.B ls
[\\fI\\,OPTION\\/\\fR]...
.SH DESCRIPTION
.\\" Add any additional description here
.PP
List information about the FILEs (the current directory by default).
Sort entries alphabetically if none of \\fB\\-cftuvSUX\\fR is specified.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\\fB\\-a\\fR, \\fB\\-\\-all\\fR
do not ignore entries starting with .
.TP
\\fB\\-\\-block\\-size\\fR=\\fI\\,SIZE\\/\\fR
with \\fB\\-l\\fR, scale sizes by SIZE when printing them;
e.g., '\\-\\-block\\-size=M'; see SIZE format below
.PP
The SIZE argument is an integer and optional unit (example: 10K is 10*1024).
Units are K,M,G,T,P,E,Z,Y,R,Q (powers of 1024) or KB,MB,... (powers of 1000).
Binary prefixes can be used, too: KiB=K, MiB=M, and so on.
.PP
The TIME_STYLE argument can be full\\-iso, long\\-iso, iso, locale, or +FORMAT.
FORMAT is interpreted like in \\fBdate\\fP(1).
.SH AUTHOR
Written by Richard M. Stallman and David MacKenzie.
.SH "REPORTING BUGS"
GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
.SH COPYRIGHT
Copyright \\(co 2023 Free Software Foundation, Inc.
.SH "SEE ALSO"
\\fBdircolors\\fP(1)
"""

_FOLD_LIKE = """\
.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.48.5.
.TH FOLD "1" "January 2026" "GNU coreutils 9.4" "User Commands"
.SH NAME
fold \\- wrap each input line to fit in specified width
.SH SYNOPSIS
.B fold
[\\fI\\,OPTION\\/\\fR]...
.SH DESCRIPTION
.\\" Add any additional description here
.PP
Wrap input lines in each FILE, writing to standard output.
.PP
With no FILE, or when FILE is \\-, read standard input.
.TP
\\fB\\-b\\fR, \\fB\\-\\-bytes\\fR
count bytes rather than columns
.TP
\\fB\\-s\\fR, \\fB\\-\\-spaces\\fR
break at spaces
.SH AUTHOR
Written by David MacKenzie.
.SH "REPORTING BUGS"
GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
.SH COPYRIGHT
Copyright \\(co 2023 Free Software Foundation, Inc.
.SH "SEE ALSO"
\\fBfmt\\fP(1)
"""

# Trimmed fixture of `gum`'s page: mango-kong over muesli/roff emits no
# marker, an empty DESCRIPTION, and a body of nothing but `.TP` entries.
_GUM_LIKE = """\
.TH GUM 1 "2026-08-20" "gum" "A tool for glamorous shell scripts."
.SH NAME
gum - A tool for glamorous shell scripts.
.SH DESCRIPTION
.SH OPTIONS
.TP
\\fB-h, --help\\fP
Show context-sensitive help.
.TP
\\fB-v, --version\\fP
Print the version number
"""

# Trimmed fixture of the real `fzf.1` page: a hand-written page with no
# marker, structured entirely with `.br`/`.TP`/`.RS` and never a `.PP`. The
# regression case for the macro-gated measure: it must not score this at
# zero just because it carries no paragraph macro.
_FZF_LIKE = """\
.TH fzf 1 "Apr 2026" "fzf 0.71.0" "fzf - a command-line fuzzy finder"
.SH NAME
fzf - a command-line fuzzy finder
.SH DESCRIPTION
fzf is an interactive filter program for any kind of list.
.br
It implements a "fuzzy" matching algorithm, so you can quickly type in
patterns with omitted characters and still get the results you want.
.SH OPTIONS
.TP
.B "\\-x, \\-\\-extended"
Extended-search mode. Enabled by default. You can disable it with \\fB+x\\fR
or \\fB\\-\\-no\\-extended\\fR.
.br
This is the mode most users want most of the time.
.RS
.TP
.B "\\-e, \\-\\-exact"
Enable exact-match, which requires every character in the query to be
present in the input line, in the given order.
.TP
.B "\\-i, \\-\\-ignore\\-case"
Case-insensitive match, the default unless the query itself has an
uppercase character.
.RE
"""

# Trimmed fixture modeled on the real `tmux.1`: BSD mdoc, `.Dd`/`.Dt` at the
# top, sections marked `.Sh` and flag entries `.It` inside `.Bl`/`.El` lists,
# never a `.SH` or `.TP` anywhere.
_TMUX_LIKE = """\
.Dd August 23, 2026
.Dt TMUX 1
.Sh NAME
.Nm tmux
.Nd terminal multiplexer
.Sh SYNOPSIS
.Nm tmux
.Op Fl 2CDluvV
.Op Fl c Ar shell-command
.Sh DESCRIPTION
tmux is a terminal multiplexer.
.Bl -tag -width Ds
.It Fl 2
Force tmux to assume the terminal supports 256 colours.
.It Fl C
Start in control mode.
.It Fl l
Behave as a login shell.
.El
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl f Ar file
Specify an alternative configuration file.
.It Fl L Ar socket-name
Specify a name for the server socket.
.El
"""

# No macro from either dialect's marker set.
_NEITHER_DIALECT = """\
plain text with no roff macros at all
just prose, nothing structural
"""


def test_is_help2man_manpage_detects_gzip_page(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.gz"
    with gzip.open(manpage, "wt", encoding="utf-8") as file:
        file.write(
            '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n'
        )

    assert is_help2man_manpage(manpage)


def test_is_help2man_manpage_detects_zstd_page(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.zst"
    with zstandard.open(manpage, "wt", encoding="utf-8") as file:
        file.write(
            '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n'
        )

    assert is_help2man_manpage(manpage)


def test_find_help_derived_manpages_scans_active_manpath(
    monkeypatch, tmp_path: Path
) -> None:
    manpath = tmp_path / "share" / "man"
    man1 = manpath / "man1"
    man1.mkdir(parents=True)
    generated = man1 / "generated.1"
    generated.write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )
    localized = manpath / "fr" / "man1" / "generated.1"
    localized.parent.mkdir(parents=True)
    localized.write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )
    (man1 / "help2man.1").write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )
    (man1 / "vendor.1").write_text(".TH VENDOR 1\n", encoding="utf-8")
    (man1 / "index.db").write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )
    calls: list[list[str]] = []
    scanned: list[None] = []
    totals: list[int] = []

    def fake_run(args: list[str], **kwargs: object) -> object:
        calls.append(args)
        return type("Result", (), {"returncode": 0, "stdout": str(manpath)})()

    monkeypatch.setattr(manpages.subprocess, "run", fake_run)

    assert find_help_derived_manpages(
        "/usr/bin/manpath",
        on_scan=lambda: scanned.append(None),
        on_start=totals.append,
    ) == [
        manpages.HelpDerivedManpage("generated", "1", generated),
        manpages.HelpDerivedManpage("help2man", "1", man1 / "help2man.1"),
    ]
    assert calls == [["/usr/bin/manpath"]]
    assert len(scanned) == 5
    assert totals == [5]


def test_find_repo_manpage_matches_bin_dash_pattern_in_man_dir(tmp_path: Path) -> None:
    man_dir = tmp_path / "man"
    man_dir.mkdir()
    manpage = man_dir / "tool-sub.1"
    manpage.write_text(".TH TOOL-SUB 1\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "tool") == manpage


def test_find_repo_manpage_matches_at_repo_root(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.6"
    manpage.write_text(".TH TOOL 6\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "tool") == manpage


def test_find_repo_manpage_matches_compressed_page(tmp_path: Path) -> None:
    doc_dir = tmp_path / "doc"
    doc_dir.mkdir()
    manpage = doc_dir / "pandoc.1.gz"
    with gzip.open(manpage, "wt", encoding="utf-8") as file:
        file.write(".TH PANDOC 1\n")

    assert find_repo_manpage(tmp_path, "pandoc") == manpage


def test_find_repo_manpage_reaches_share_man(tmp_path: Path) -> None:
    man1_dir = tmp_path / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    manpage = man1_dir / "tool.1"
    manpage.write_text(".TH TOOL 1\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "tool") == manpage


def test_find_repo_manpage_skips_help2man_generated_pages(tmp_path: Path) -> None:
    doc_dir = tmp_path / "doc"
    doc_dir.mkdir()
    (doc_dir / "tool.1").write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )

    assert find_repo_manpage(tmp_path, "tool") is None


def test_find_repo_manpage_ignores_unrelated_trees(tmp_path: Path) -> None:
    vendor_dir = tmp_path / "vendor" / "man"
    vendor_dir.mkdir(parents=True)
    (vendor_dir / "tool.1").write_text(".TH TOOL 1\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "tool") is None


def test_find_repo_manpage_no_match_returns_none(tmp_path: Path) -> None:
    assert find_repo_manpage(tmp_path, "tool") is None


def test_find_repo_manpage_prefers_exact_name_over_subcommand_variant(
    tmp_path: Path,
) -> None:
    man_dir = tmp_path / "man" / "man1"
    man_dir.mkdir(parents=True)
    exact = man_dir / "fzf.1"
    exact.write_text(".TH FZF 1\n", encoding="utf-8")
    (man_dir / "fzf-tmux.1").write_text(".TH FZF-TMUX 1\n", encoding="utf-8")

    assert find_repo_manpage(tmp_path, "fzf") == exact


def test_find_install_root_manpages_returns_sibling_pages(tmp_path: Path) -> None:
    """The pandoc case: one package root, three binaries' pages side by side."""
    man1_dir = tmp_path / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    pages = []
    for name in ("pandoc.1.gz", "pandoc-lua.1.gz", "pandoc-server.1.gz"):
        page = man1_dir / name
        with gzip.open(page, "wt", encoding="utf-8") as file:
            file.write(".TH PANDOC 1\n")
        pages.append(page)

    assert find_install_root_manpages(tmp_path, "pandoc") == sorted(pages)


def test_find_install_root_manpages_keeps_help2man_generated_pages(
    tmp_path: Path,
) -> None:
    """Unlike `find_repo_manpage`, no generator filter: tier 1 is authoritative
    by construction (ADR-0016), not by quality (deferred past tier 1)."""
    manpage = tmp_path / "tool.1"
    manpage.write_text(
        '.\\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.49.3.\n',
        encoding="utf-8",
    )

    assert find_install_root_manpages(tmp_path, "tool") == [manpage]


def test_find_install_root_manpages_ignores_backup_copies(tmp_path: Path) -> None:
    """mise leaves numbered backups (`fzf.1.1`, `fzf.1.12`, ...) next to a
    reinstalled tool's page; fnmatch's fixed-width `[1-9]` class does not
    match their extra `.N` suffix."""
    exact = tmp_path / "fzf.1"
    exact.write_text(".TH FZF 1\n", encoding="utf-8")
    (tmp_path / "fzf.1.1").write_text(".TH FZF 1\n", encoding="utf-8")
    (tmp_path / "fzf.1.12").write_text(".TH FZF 1\n", encoding="utf-8")

    assert find_install_root_manpages(tmp_path, "fzf") == [exact]


def test_find_install_root_manpages_no_match_returns_empty(tmp_path: Path) -> None:
    assert find_install_root_manpages(tmp_path, "tool") == []


def test_find_install_root_manpages_reaches_one_release_wrapper_dir(
    tmp_path: Path,
) -> None:
    """The `gh`/`pastel` case: mise keeps a release tarball's own top-level
    folder (`gh_2.90.0_linux_amd64/`) between the install root and
    `share/man/man1/`, one level deeper than `find_repo_manpage` reaches."""
    man1_dir = tmp_path / "gh_2.90.0_linux_amd64" / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    exact = man1_dir / "gh.1"
    exact.write_text(".TH GH 1\n", encoding="utf-8")
    sub = man1_dir / "gh-issue-list.1"
    sub.write_text(".TH GH-ISSUE-LIST 1\n", encoding="utf-8")

    assert find_install_root_manpages(tmp_path, "gh") == sorted([exact, sub])


def test_find_install_root_manpages_does_not_reach_two_wrapper_levels(
    tmp_path: Path,
) -> None:
    """The tolerance is one wrapper level, not unbounded depth."""
    man1_dir = tmp_path / "release" / "extra" / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    (man1_dir / "tool.1").write_text(".TH TOOL 1\n", encoding="utf-8")

    assert find_install_root_manpages(tmp_path, "tool") == []


def test_find_install_root_manpages_prunes_irrelevant_trees(
    tmp_path: Path, monkeypatch
) -> None:
    """A large irrelevant tree (a venv's `lib/site-packages/`, say) must not
    be descended into once its wrapper-tolerant top level rules it out --
    the regression this fixes: an unpruned walk would visit every nested
    directory below `lib/` just to find nothing there."""
    nested = tmp_path / "lib" / "site-packages"
    for index in range(50):
        nested = nested / f"pkg{index}"
    nested.mkdir(parents=True)
    (nested / "module.py").write_text("", encoding="utf-8")

    man1_dir = tmp_path / "share" / "man" / "man1"
    man1_dir.mkdir(parents=True)
    manpage = man1_dir / "tool.1"
    manpage.write_text(".TH TOOL 1\n", encoding="utf-8")

    visited: list[Path] = []
    real_walk = manpages.os.walk

    def counting_walk(top, *args, **kwargs):
        for entry in real_walk(top, *args, **kwargs):
            visited.append(Path(entry[0]))
            yield entry

    monkeypatch.setattr(manpages.os, "walk", counting_walk)

    assert find_install_root_manpages(tmp_path, "tool") == [manpage]
    assert all("site-packages" not in path.parts for path in visited)
    # Bounded by the real tree (root, lib, share, share/man, share/man/man1),
    # not by the 50-level irrelevant tree below `lib/site-packages/`.
    assert len(visited) < 10


def test_find_installed_manpage_path_returns_first_hit(
    monkeypatch, tmp_path: Path
) -> None:
    target = tmp_path / "tool.1.gz"

    def fake_run(args: list[str], **kwargs: object) -> object:
        assert args == ["/usr/bin/man", "-w", "tool"]
        return type("Result", (), {"returncode": 0, "stdout": f"{target}\n"})()

    monkeypatch.setattr(manpages.subprocess, "run", fake_run)
    assert find_installed_manpage_path("/usr/bin/man", "tool") == target


def test_find_installed_manpage_path_missing_returns_none(monkeypatch) -> None:
    def fake_run(args: list[str], **kwargs: object) -> object:
        return type("Result", (), {"returncode": 1, "stdout": ""})()

    monkeypatch.setattr(manpages.subprocess, "run", fake_run)
    assert find_installed_manpage_path("/usr/bin/man", "nonexistent") is None


def test_read_manpage_source_decompresses_gzip(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.gz"
    content = ".TH TOOL 1\n.SH NAME\ntool \\- demo\n"
    with gzip.open(manpage, "wt", encoding="utf-8") as file:
        file.write(content)

    assert read_manpage_source(manpage) == content


def test_read_manpage_source_decompresses_zstd(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.zst"
    content = ".TH TOOL 1\n.SH NAME\ntool \\- demo\n"
    with zstandard.open(manpage, "wt", encoding="utf-8") as file:
        file.write(content)

    assert read_manpage_source(manpage) == content


def test_read_manpage_source_reads_plain_file(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1"
    content = ".TH TOOL 1\n"
    manpage.write_text(content, encoding="utf-8")

    assert read_manpage_source(manpage) == content


def test_detect_generator_from_content_recognizes_each_marker() -> None:
    markers = {
        Generator.HELP2MAN: "It was generated by help2man 1.49.3.",
        Generator.POD_MAN: "Automatically generated by Pod::Man 4.14",
        Generator.PANDOC: "Automatically generated by Pandoc 3.1",
        Generator.TXT2MAN: "Text automatically generated by txt2man",
        Generator.DOCBOOK_XSL: "Generator: DocBook XSL Stylesheets V1.79.2",
        Generator.PO4A: "This page was generated with po4a",
        Generator.COBRA: "Auto generated by spf13/cobra on 1-Jan-2026",
    }
    for generator, marker in markers.items():
        assert (
            detect_generator_from_content(f'.\\" {marker}\n.TH TOOL 1\n') is generator
        )


def test_detect_generator_from_content_returns_none_without_marker() -> None:
    assert detect_generator_from_content(_GUM_LIKE) is None


def test_detect_generator_reads_gzip_page(tmp_path: Path) -> None:
    manpage = tmp_path / "tool.1.gz"
    with gzip.open(manpage, "wt", encoding="utf-8") as file:
        file.write(_LS_LIKE)

    assert detect_generator(manpage) is Generator.HELP2MAN


def test_count_words_does_not_require_a_paragraph_macro() -> None:
    """Regression case for the macro-gated measure this replaced: a
    hand-written page structured with `.br`/`.TP`/`.RS` and no `.PP`
    anywhere must still score in the hundreds, not zero."""
    assert count_words(_FZF_LIKE) > 100


def test_count_words_separates_ls_from_fold_despite_shared_marker() -> None:
    """Both help2man-generated, both 7 sections; `ls.1` carries more
    visible prose than `fold.1` because help2man's `--include` spliced
    extra paragraphs into one and not the other."""
    ls_sections = _LS_LIKE.count("\n.SH ")
    fold_sections = _FOLD_LIKE.count("\n.SH ")
    assert ls_sections == fold_sections == 7

    assert count_words(_LS_LIKE) > count_words(_FOLD_LIKE)
    assert count_words(_FOLD_LIKE) > 0


def test_count_words_is_low_for_a_bare_tp_only_page() -> None:
    """`gum`'s page has as many `.TP` entries as `fzf`'s trimmed fixture but
    far fewer words in each, since none carries more than a short label."""
    assert count_words(_GUM_LIKE) < count_words(_FZF_LIKE)


def test_count_tp_entries_counts_each_tp_macro() -> None:
    assert count_tp_entries(_GUM_LIKE) == 2
    assert count_tp_entries(_FZF_LIKE) == 3


def test_extract_sections_returns_top_level_sh_titles_in_order() -> None:
    assert extract_sections(_LS_LIKE) == [
        "NAME",
        "SYNOPSIS",
        "DESCRIPTION",
        "AUTHOR",
        "REPORTING BUGS",
        "COPYRIGHT",
        "SEE ALSO",
    ]


def test_extract_sections_ignores_ss_subsections() -> None:
    content = ".SH NAME\ntool\n.SS Details\nmore\n.SH DESCRIPTION\ntext\n"
    assert extract_sections(content) == ["NAME", "DESCRIPTION"]


def test_detect_dialect_from_content_recognizes_mdoc() -> None:
    assert detect_dialect_from_content(_TMUX_LIKE) is Dialect.MDOC


def test_detect_dialect_from_content_recognizes_man_regression_guard() -> None:
    """`fzf.1` must keep classifying as man(7) after mdoc detection lands."""
    assert detect_dialect_from_content(_LS_LIKE) is Dialect.MAN
    assert detect_dialect_from_content(_FZF_LIKE) is Dialect.MAN


def test_detect_dialect_from_content_returns_unknown_for_neither_macro_set() -> None:
    assert detect_dialect_from_content(_NEITHER_DIALECT) is Dialect.UNKNOWN


def test_count_tp_entries_counts_it_as_flag_entries_for_mdoc() -> None:
    assert count_tp_entries(_TMUX_LIKE, Dialect.MDOC) == 5


def test_extract_sections_returns_sh_titles_for_mdoc() -> None:
    assert extract_sections(_TMUX_LIKE, Dialect.MDOC) == [
        "NAME",
        "SYNOPSIS",
        "DESCRIPTION",
        "OPTIONS",
    ]


def test_has_examples_section_matches_examples_or_usage_case_insensitively() -> None:
    assert has_examples_section(["NAME", "EXAMPLES"])
    assert has_examples_section(["NAME", "Usage"])
    assert not has_examples_section(extract_sections(_LS_LIKE))
    assert not has_examples_section(extract_sections(_FOLD_LIKE))


def test_find_installed_manpages_includes_pages_without_a_marker(
    monkeypatch, tmp_path: Path
) -> None:
    manpath = tmp_path / "share" / "man"
    man1 = manpath / "man1"
    man1.mkdir(parents=True)
    generated = man1 / "generated.1"
    generated.write_text(_LS_LIKE, encoding="utf-8")
    bare = man1 / "bare.1"
    bare.write_text(_GUM_LIKE, encoding="utf-8")
    (man1 / "index.db").write_text(_GUM_LIKE, encoding="utf-8")

    def fake_run(args: list[str], **kwargs: object) -> object:
        return type("Result", (), {"returncode": 0, "stdout": str(manpath)})()

    monkeypatch.setattr(manpages.subprocess, "run", fake_run)

    assert find_installed_manpages("/usr/bin/manpath") == [
        manpages.HelpDerivedManpage("bare", "1", bare),
        manpages.HelpDerivedManpage("generated", "1", generated),
    ]


def test_select_primary_manpage_prefers_exact_over_subcommand() -> None:
    """`pandoc.1.gz`'s own package, not one of its sibling binaries' pages."""
    exact = Path("pandoc.1.gz")
    sibling = Path("pandoc-lua.1.gz")

    assert select_primary_manpage([sibling, exact], "pandoc") == exact


def test_select_primary_manpage_no_match_returns_none() -> None:
    assert select_primary_manpage([Path("pandoc-lua.1.gz")], "somethingelse") is None


def test_manpage_documents_matches_th_title() -> None:
    content = '.TH PANDOC "1" "January 2024" "pandoc 3.1.2" "User Commands"\n'
    assert manpage_documents(content, "pandoc") is True
    assert manpage_documents(content, "someothertool") is False


def test_manpage_documents_matches_mdoc_title() -> None:
    content = ".Dd January 1, 2024\n.Dt TMUX 1\n.Sh NAME\n"
    assert manpage_documents(content, "tmux") is True


def test_manpage_documents_no_title_is_false() -> None:
    assert manpage_documents("no macros here\n", "pandoc") is False
