"""Inspect installed manpages before treating them as authoritative."""

import bz2
import fnmatch
import gzip
import lzma
import os
import re
import subprocess
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import TextIO

from ..exceptions import ManiacError
from ..logging import logger

HELP2MAN_MARKER = "it was generated by help2man"
_PREFIX_BYTES = 8_192
REPO_MANPAGE_DIRS = {"man", "doc", "docs"}


class Generator(Enum):
    """A manpage generator recognized from a comment or field marker.

    Internal to classification -- never presented to the user. A marker names
    what produced a page, not whether its input was good; Pandoc, Pod::Man and
    DocBook XSL convert prose a human wrote, so this is not a quality axis.
    """

    HELP2MAN = "help2man"
    POD_MAN = "pod::man"
    PANDOC = "pandoc"
    TXT2MAN = "txt2man"
    DOCBOOK_XSL = "docbook_xsl"
    PO4A = "po4a"
    COBRA = "cobra"


# Case-insensitive substrings, checked in the first _PREFIX_BYTES of the
# decompressed page. Cobra's marker is opt-out upstream (DisableAutoGenTag),
# so its absence proves nothing.
_GENERATOR_MARKERS: dict[Generator, str] = {
    Generator.HELP2MAN: HELP2MAN_MARKER,
    Generator.POD_MAN: "automatically generated by pod::man",
    Generator.PANDOC: "automatically generated by pandoc",
    Generator.TXT2MAN: "text automatically generated by txt2man",
    Generator.DOCBOOK_XSL: "generator: docbook xsl stylesheets",
    Generator.PO4A: "generated with po4a",
    Generator.COBRA: "auto generated by spf13/cobra",
}

_ROFF_ESCAPES: list[tuple[str, str]] = [
    (r"\\f[A-Z]", ""),  # font change: \fB \fI \fR
    (r"\\\([a-zA-Z]{2}", ""),  # named glyph: \(co \(aq
    (r"\\-", "-"),
    (r"\\[,/&]", ""),  # zero-width joins: \, \/ \&
]

# A `.\"` line is a source comment, invisible in rendered output.
_COMMENT_PREFIX = '.\\"'

_EXAMPLES_SECTIONS = {"EXAMPLES", "USAGE"}


@dataclass(frozen=True, slots=True)
class ManpageStatus:
    """Whether an installed page exists and is generated by help2man."""

    exists: bool
    is_help2man: bool

    @property
    def is_usable(self) -> bool:
        """Whether the installed page is not generated by help2man."""
        return self.exists and not self.is_help2man


@dataclass(frozen=True, slots=True)
class HelpDerivedManpage:
    """A recognized help-derived manpage and its installed location."""

    name: str
    section: str
    path: Path


def find_installed_manpage_path(man_bin: str, tool_name: str) -> Path | None:
    """Locate the installed manpage path for ``tool_name`` via ``man -w``."""
    result = subprocess.run(
        [man_bin, "-w", tool_name], capture_output=True, text=True, check=False
    )
    if result.returncode != 0 or not result.stdout.strip():
        return None
    first_line = result.stdout.strip().splitlines()[0].strip()
    return Path(first_line) if first_line else None


def read_manpage_source(path: Path) -> str:
    """Read and fully decompress an installed manpage's roff source."""
    with _opener_for(path)(path, "rt", encoding="utf-8", errors="replace") as file:
        return file.read()


def inspect_manpage(man_bin: str, tool_name: str) -> ManpageStatus:
    """Inspect ``tool_name``'s installed page without rendering it."""
    result = subprocess.run(
        [man_bin, "-w", tool_name], capture_output=True, text=True, check=False
    )
    if result.returncode != 0 or not result.stdout.strip():
        return ManpageStatus(exists=False, is_help2man=False)

    paths = [Path(line) for line in result.stdout.splitlines() if line.strip()]
    return ManpageStatus(
        exists=True,
        is_help2man=bool(paths) and all(is_help2man_manpage(path) for path in paths),
    )


def is_help2man_manpage(path: Path) -> bool:
    """Whether a roff file carries help2man's generated-file marker."""
    try:
        prefix = _read_prefix(path)
    except (OSError, UnicodeError) as error:
        logger.debug("Unable to inspect manpage", path=str(path), error=str(error))
        return False
    return HELP2MAN_MARKER in prefix.lower()


def is_help2man_content(content: str) -> bool:
    """Whether roff content starts with help2man's generated-file marker."""
    return HELP2MAN_MARKER in content[:_PREFIX_BYTES].lower()


def detect_generator(path: Path) -> Generator | None:
    """Identify the generator of an installed page from its marker, if any."""
    try:
        prefix = _read_prefix(path)
    except (OSError, UnicodeError) as error:
        logger.debug("Unable to inspect manpage", path=str(path), error=str(error))
        return None
    return detect_generator_from_content(prefix)


def detect_generator_from_content(content: str) -> Generator | None:
    """Identify the generator of roff content from its marker, if any.

    A prior, not a verdict: absence means no known marker, not that a human
    wrote the page, and Cobra pages can suppress the marker entirely.
    """
    prefix = content[:_PREFIX_BYTES].lower()
    for generator, marker in _GENERATOR_MARKERS.items():
        if marker in prefix:
            return generator
    return None


def count_words(content: str) -> int:
    """Count words in a page's visible body text, independent of which macro carries it.

    Structural fact for pages a marker cannot discriminate: help2man's own
    `ls.1` and `fold.1` carry the same marker and section count but differ
    by an order of magnitude in visible prose. Gating this on a specific
    paragraph macro such as `.PP` was tried and rejected -- it scored a
    hand-written page structured with `.br`/`.TP`/`.RS` (`fzf.1`) or `.IP`
    (`just.1`) at zero, the false positive ADR-0012 forbids. Every line
    counts except a `.\\"` comment, invisible in rendered output; a macro
    line still contributes whatever text follows its name, such as `.TH`'s
    title or `.B`'s argument.

    Deliberately not divided by `.TP` count or any other fact here: a
    single scalar cannot order both a marker-free flag dump (`gum.1`,
    thin) and a terse page with few flags (`fold.1`, not thin) correctly
    at once. Combining facts into a verdict is deferred, not this
    function's job.
    """
    words: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(_COMMENT_PREFIX):
            continue
        if stripped.startswith("."):
            _, _, stripped = stripped.partition(" ")
        words.append(stripped)

    text = " ".join(words)
    for pattern, replacement in _ROFF_ESCAPES:
        text = re.sub(pattern, replacement, text)
    return len(text.split())


def count_tp_entries(content: str) -> int:
    """Count `.TP` entries: each is one flag or term/description pair."""
    return sum(1 for line in content.splitlines() if line.strip().startswith(".TP"))


def extract_sections(content: str) -> list[str]:
    """Return top-level `.SH` section titles, in document order."""
    sections: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped.startswith(".SH"):
            continue
        _, _, title = stripped.partition(" ")
        sections.append(title.strip().strip('"'))
    return sections


def has_examples_section(sections: list[str]) -> bool:
    """Whether an EXAMPLES or USAGE section is present, case-insensitively."""
    return any(section.upper() in _EXAMPLES_SECTIONS for section in sections)


def find_repo_manpage(repo_dir: Path, binary_name: str) -> Path | None:
    """Find a hand-authored manpage for ``binary_name`` shipped in a repository checkout.

    Mirrors the glob mise's ``system-install`` task uses to link tool-shipped
    manpages (``<bin>.[1-9]`` and ``<bin>-*.[1-9]``), but scoped to the
    repository root and its ``man``/``doc``/``docs`` trees rather than an
    entire installed tool directory, since a checkout can otherwise hold
    unrelated fixtures and vendored sources.
    """
    exact_pattern = f"{binary_name}.[1-9]"
    subcommand_pattern = f"{binary_name}-*.[1-9]"
    candidates = sorted(_iter_repo_manpage_files(repo_dir))

    for pattern in (exact_pattern, subcommand_pattern):
        for path in candidates:
            if fnmatch.fnmatch(path.name, pattern) and not is_help2man_manpage(path):
                return path
    return None


def _iter_repo_manpage_files(repo_dir: Path) -> Iterator[Path]:
    """Yield files at a repository root and under its man/doc/docs trees."""
    if not repo_dir.is_dir():
        return
    yield from (item for item in repo_dir.iterdir() if item.is_file())
    for root, directories, files in os.walk(repo_dir):
        rel_dir = Path(root).relative_to(repo_dir)
        directories[:] = [d for d in directories if not d.startswith(".")]
        if rel_dir == Path(".") or rel_dir.parts[0].lower() not in REPO_MANPAGE_DIRS:
            continue
        for filename in files:
            yield Path(root, filename)


def find_help_derived_manpages(
    manpath_bin: str,
    on_scan: Callable[[], None] | None = None,
    on_start: Callable[[int], None] | None = None,
) -> list[HelpDerivedManpage]:
    """List recognized help-derived pages in the active manpath."""
    pages = [
        page
        for page in _scan_manpath(manpath_bin, on_scan, on_start)
        if is_help2man_manpage(page.path)
    ]
    return _deduplicate_help_derived_manpages(pages)


def find_installed_manpages(
    manpath_bin: str,
    on_scan: Callable[[], None] | None = None,
    on_start: Callable[[int], None] | None = None,
) -> list[HelpDerivedManpage]:
    """List every identifiable page in the active manpath, generator or not."""
    return _deduplicate_help_derived_manpages(
        list(_scan_manpath(manpath_bin, on_scan, on_start))
    )


def _scan_manpath(
    manpath_bin: str,
    on_scan: Callable[[], None] | None,
    on_start: Callable[[int], None] | None,
) -> Iterator[HelpDerivedManpage]:
    """Identify every regular file in the active manpath as a candidate page."""
    result = subprocess.run([manpath_bin], capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise ManiacError("Could not determine the active manpath.")

    manpaths = [Path(entry) for entry in result.stdout.strip().split(":") if entry]
    paths = [path for manpath in manpaths for path in _iter_manpage_files(manpath)]
    if on_start is not None:
        on_start(len(paths))

    for path in paths:
        if on_scan is not None:
            on_scan()
        identity = _manpage_identity(path)
        if identity is None:
            continue
        name, section = identity
        yield HelpDerivedManpage(name=name, section=section, path=path)


def _deduplicate_help_derived_manpages(
    pages: list[HelpDerivedManpage],
) -> list[HelpDerivedManpage]:
    """Keep the shortest path for each name and section."""
    unique_pages: dict[tuple[str, str], HelpDerivedManpage] = {}
    for page in sorted(pages, key=lambda page: (len(page.path.parts), str(page.path))):
        unique_pages.setdefault((page.name, page.section), page)
    return sorted(
        unique_pages.values(),
        key=lambda page: (page.name, page.section, str(page.path)),
    )


def _iter_manpage_files(manpath: Path) -> Iterator[Path]:
    """Yield regular files from one local manpath directory."""
    if not manpath.is_dir():
        logger.debug("Skipping unavailable manpath directory", path=str(manpath))
        return

    for root, directories, files in os.walk(manpath):
        directories.sort()
        for filename in sorted(files):
            path = Path(root, filename)
            if path.is_file():
                yield path


def _manpage_identity(path: Path) -> tuple[str, str] | None:
    """Extract a page name and section from a standard manpage filename."""
    directory = path.parent.name
    if not directory.startswith("man") or len(directory) == 3:
        return None

    filename = path.name
    if path.suffix in {".bz2", ".gz", ".lzma", ".xz"}:
        filename = Path(filename).stem

    name, separator, section = filename.rpartition(".")
    if not separator or not name or not section.startswith(directory[3:]):
        return None
    return name, section


def _opener_for(path: Path) -> Callable[..., TextIO]:
    """Pick the file opener for a plain or standard-compressed manpage."""
    match path.suffix:
        case ".gz":
            return gzip.open
        case ".bz2":
            return bz2.open
        case ".xz" | ".lzma":
            return lzma.open
        case _:
            return open


def _read_prefix(path: Path) -> str:
    """Read enough of a plain or standard-compressed manpage to identify it."""
    with _opener_for(path)(path, "rt", encoding="utf-8", errors="replace") as file:
        return file.read(_PREFIX_BYTES)
