"""Inspect installed manpages before treating them as authoritative."""

import bz2
import fnmatch
import gzip
import io
import lzma
import os
import re
import subprocess
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import TextIO

import zstandard

from ..exceptions import ManiacError
from ..logging import logger

HELP2MAN_MARKER = "it was generated by help2man"
_PREFIX_BYTES = 8_192
# `share/man` is the FHS convention (`<prefix>/share/man/man<N>`); the other
# three are the ad hoc trees repos put hand-authored pages in directly.
REPO_MANPAGE_DIRS: tuple[tuple[str, ...], ...] = (
    ("man",),
    ("doc",),
    ("docs",),
    ("share", "man"),
)
_COMPRESSION_SUFFIXES = ("", ".gz", ".bz2", ".xz", ".zst")


class Generator(Enum):
    """A manpage generator recognized from a comment or field marker.

    Internal to classification -- never presented to the user. A marker names
    what produced a page, not whether its input was good; Pandoc, Pod::Man and
    DocBook XSL convert prose a human wrote, so this is not a quality axis.
    """

    HELP2MAN = "help2man"
    POD_MAN = "pod::man"
    PANDOC = "pandoc"
    TXT2MAN = "txt2man"
    DOCBOOK_XSL = "docbook_xsl"
    PO4A = "po4a"
    COBRA = "cobra"


# Case-insensitive substrings, checked in the first _PREFIX_BYTES of the
# decompressed page. Cobra's marker is opt-out upstream (DisableAutoGenTag),
# so its absence proves nothing.
_GENERATOR_MARKERS: dict[Generator, str] = {
    Generator.HELP2MAN: HELP2MAN_MARKER,
    Generator.POD_MAN: "automatically generated by pod::man",
    Generator.PANDOC: "automatically generated by pandoc",
    Generator.TXT2MAN: "text automatically generated by txt2man",
    Generator.DOCBOOK_XSL: "generator: docbook xsl stylesheets",
    Generator.PO4A: "generated with po4a",
    Generator.COBRA: "auto generated by spf13/cobra",
}


class Dialect(Enum):
    """Which roff macro set a page is written in.

    man(7) marks sections `.SH` and flag entries `.TP`; BSD mdoc marks them
    `.Sh` and `.It`. A classifier that only understands one dialect
    misreads every page in the other -- `tmux.1` has 1017 `.It` and zero
    `.TP`, so `tp_count`/`sections` must be computed against the dialect a
    page is actually written in, not assumed to be man(7).
    """

    MAN = "man"
    MDOC = "mdoc"
    UNKNOWN = "unknown"


# Distinctive macros, checked at line starts in the page prefix. `.Dd`/`.Dt`
# (the mdoc document-date/title pair) are the strongest mdoc signal but need
# no separate weighting: real mdoc pages carry many more macro lines than
# man(7) impostors could fake with a single macro.
_MDOC_MARKERS = re.compile(r"(?m)^\.(?:Dd|Dt|Sh|Bl|It|Nm|Fl|Op|Ar|Cm)\b")
_MAN_MARKERS = re.compile(r"(?m)^\.(?:TH|SH|TP|IP|PP|B|BR|BI)\b")


def detect_dialect_from_content(content: str) -> Dialect:
    """Identify a page's roff dialect by which macro set dominates its prefix.

    Cheap by construction: a regex count over the same prefix bytes other
    detection already reads, no roff parsing. Neither macro set present, or
    a tie between them, means unknown -- a page cannot be assumed man(7)
    just because it lacks mdoc markers.
    """
    prefix = content[:_PREFIX_BYTES]
    mdoc_count = len(_MDOC_MARKERS.findall(prefix))
    man_count = len(_MAN_MARKERS.findall(prefix))
    if mdoc_count > man_count:
        return Dialect.MDOC
    if man_count > mdoc_count:
        return Dialect.MAN
    return Dialect.UNKNOWN


_ROFF_ESCAPES: list[tuple[str, str]] = [
    (r"\\f[A-Z]", ""),  # font change: \fB \fI \fR
    (r"\\\([a-zA-Z]{2}", ""),  # named glyph: \(co \(aq
    (r"\\-", "-"),
    (r"\\[,/&]", ""),  # zero-width joins: \, \/ \&
]

# A `.\"` line is a source comment, invisible in rendered output.
_COMMENT_PREFIX = '.\\"'

_EXAMPLES_SECTIONS = {"EXAMPLES", "USAGE"}


@dataclass(frozen=True, slots=True)
class ManpageStatus:
    """Whether an installed page exists and is generated by help2man."""

    exists: bool
    is_help2man: bool

    @property
    def is_usable(self) -> bool:
        """Whether the installed page is not generated by help2man."""
        return self.exists and not self.is_help2man


@dataclass(frozen=True, slots=True)
class HelpDerivedManpage:
    """A recognized help-derived manpage and its installed location."""

    name: str
    section: str
    path: Path


def find_installed_manpage_path(man_bin: str, tool_name: str) -> Path | None:
    """Locate the installed manpage path for ``tool_name`` via ``man -w``."""
    result = subprocess.run(
        [man_bin, "-w", tool_name], capture_output=True, text=True, check=False
    )
    if result.returncode != 0 or not result.stdout.strip():
        return None
    first_line = result.stdout.strip().splitlines()[0].strip()
    return Path(first_line) if first_line else None


def read_manpage_source(path: Path) -> str:
    """Read and fully decompress an installed manpage's roff source."""
    with _opener_for(path)(path, "rt", encoding="utf-8", errors="replace") as file:
        return file.read()


def inspect_manpage(man_bin: str, tool_name: str) -> ManpageStatus:
    """Inspect ``tool_name``'s installed page without rendering it."""
    result = subprocess.run(
        [man_bin, "-w", tool_name], capture_output=True, text=True, check=False
    )
    if result.returncode != 0 or not result.stdout.strip():
        return ManpageStatus(exists=False, is_help2man=False)

    paths = [Path(line) for line in result.stdout.splitlines() if line.strip()]
    return ManpageStatus(
        exists=True,
        is_help2man=bool(paths) and all(is_help2man_manpage(path) for path in paths),
    )


def is_help2man_manpage(path: Path) -> bool:
    """Whether a roff file carries help2man's generated-file marker."""
    try:
        prefix = _read_prefix(path)
    except (OSError, UnicodeError) as error:
        logger.debug("Unable to inspect manpage", path=str(path), error=str(error))
        return False
    return HELP2MAN_MARKER in prefix.lower()


def is_help2man_content(content: str) -> bool:
    """Whether roff content starts with help2man's generated-file marker."""
    return HELP2MAN_MARKER in content[:_PREFIX_BYTES].lower()


def detect_generator(path: Path) -> Generator | None:
    """Identify the generator of an installed page from its marker, if any."""
    try:
        prefix = _read_prefix(path)
    except (OSError, UnicodeError) as error:
        logger.debug("Unable to inspect manpage", path=str(path), error=str(error))
        return None
    return detect_generator_from_content(prefix)


def detect_generator_from_content(content: str) -> Generator | None:
    """Identify the generator of roff content from its marker, if any.

    A prior, not a verdict: absence means no known marker, not that a human
    wrote the page, and Cobra pages can suppress the marker entirely.
    """
    prefix = content[:_PREFIX_BYTES].lower()
    for generator, marker in _GENERATOR_MARKERS.items():
        if marker in prefix:
            return generator
    return None


def count_words(content: str) -> int:
    """Count words in a page's visible body text, independent of which macro carries it.

    Structural fact for pages a marker cannot discriminate: help2man's own
    `ls.1` and `fold.1` carry the same marker and section count but differ
    by an order of magnitude in visible prose. Gating this on a specific
    paragraph macro such as `.PP` was tried and rejected -- it scored a
    hand-written page structured with `.br`/`.TP`/`.RS` (`fzf.1`) or `.IP`
    (`just.1`) at zero, the false positive ADR-0012 forbids. Every line
    counts except a `.\\"` comment, invisible in rendered output; a macro
    line still contributes whatever text follows its name, such as `.TH`'s
    title or `.B`'s argument.

    Deliberately not divided by `.TP` count or any other fact here: a
    single scalar cannot order both a marker-free flag dump (`gum.1`,
    thin) and a terse page with few flags (`fold.1`, not thin) correctly
    at once. Combining facts into a verdict is deferred, not this
    function's job.
    """
    words: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(_COMMENT_PREFIX):
            continue
        if stripped.startswith("."):
            _, _, stripped = stripped.partition(" ")
        words.append(stripped)

    text = " ".join(words)
    for pattern, replacement in _ROFF_ESCAPES:
        text = re.sub(pattern, replacement, text)
    return len(text.split())


def count_tp_entries(content: str, dialect: Dialect = Dialect.MAN) -> int:
    """Count flag/term entries: `.TP` for man(7), `.It` for mdoc."""
    macro = ".It" if dialect is Dialect.MDOC else ".TP"
    return sum(1 for line in content.splitlines() if line.strip().startswith(macro))


def extract_sections(content: str, dialect: Dialect = Dialect.MAN) -> list[str]:
    """Return top-level section titles in document order: `.SH` for man(7), `.Sh` for mdoc."""
    macro = ".Sh" if dialect is Dialect.MDOC else ".SH"
    sections: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped.startswith(macro):
            continue
        _, _, title = stripped.partition(" ")
        sections.append(title.strip().strip('"'))
    return sections


def has_examples_section(sections: list[str]) -> bool:
    """Whether an EXAMPLES or USAGE section is present, case-insensitively."""
    return any(section.upper() in _EXAMPLES_SECTIONS for section in sections)


# `.TH` (man(7)) and `.Dt` (mdoc) both open with the page's own declared
# title as their first argument, bare or quoted.
_TH_TITLE = re.compile(r'(?m)^\.TH\s+"?([^"\s]+)"?')
_DT_TITLE = re.compile(r'(?m)^\.Dt\s+"?([^"\s]+)"?')


def manpage_documents(content: str, binary_name: str) -> bool:
    """Whether a page's own `.TH`/`.Dt` title names `binary_name` (ADR-0016 tier 2).

    A tier-2 page already matched `binary_name` by filename before this is
    called; this checks the page's own declared subject too, so a
    same-named file that documents something else is not installed
    verbatim. It does not prove the repository itself is the right
    upstream -- a wrongly resolved repository can still ship a page that
    correctly names the binary it documents (`docs/BACKLOG.md`'s
    `tmux`/`tmux-builds` case) -- only that title and filename agree.
    """
    prefix = content[:_PREFIX_BYTES]
    match = _TH_TITLE.search(prefix) or _DT_TITLE.search(prefix)
    if match is None:
        return False
    return match.group(1).strip('"').lower() == binary_name.lower()


def select_primary_manpage(paths: list[Path], binary_name: str) -> Path | None:
    """Pick the page documenting `binary_name` itself from a `local_docs()`-style list.

    Prefers an exact `<bin>.<section>` match over a `<bin>-sub.<section>`
    sibling -- naive lexical sorting would return `fzf-tmux.1` before
    `fzf.1` since `-` sorts before `.`. Mirrors `find_repo_manpage`'s own
    exact-over-subcommand ordering, applied to an already-gathered list
    (`find_install_root_manpages`'s) instead of a directory walk.
    """
    exact_patterns, subcommand_patterns = _manpage_patterns(binary_name)
    for patterns in (exact_patterns, subcommand_patterns):
        for path in paths:
            if any(fnmatch.fnmatch(path.name, pattern) for pattern in patterns):
                return path
    return None


def find_repo_manpage(repo_dir: Path, binary_name: str) -> Path | None:
    """Find a hand-authored manpage for ``binary_name`` shipped in a repository checkout.

    Mirrors the glob mise's ``system-install`` task uses to link tool-shipped
    manpages (``<bin>.[1-9]`` and ``<bin>-*.[1-9]``), extended with the
    standard compression suffixes since a shipped page is often stored
    compressed (``pandoc.1.gz``). Scoped to the repository root and its
    ``man``/``doc``/``docs``/``share/man`` trees rather than an entire
    installed tool directory, since a checkout can otherwise hold unrelated
    fixtures and vendored sources.
    """
    exact_patterns, subcommand_patterns = _manpage_patterns(binary_name)
    candidates = sorted(_iter_repo_manpage_files(repo_dir))

    for patterns in (exact_patterns, subcommand_patterns):
        for path in candidates:
            matches = any(fnmatch.fnmatch(path.name, pattern) for pattern in patterns)
            if matches and not is_help2man_manpage(path):
                return path
    return None


def find_install_root_manpages(root: Path, binary_name: str) -> list[Path]:
    """List every manpage an install root ships for ``binary_name`` (ADR-0016 tier 1).

    Same patterns as `find_repo_manpage`, but returns every match instead of
    the first and applies no generator filter: a page taken from the install
    root is the installed version by construction, so whether it happens to
    be help2man-generated is not asked here (ADR-0016 defers quality
    judgement past tier 1). The subcommand pattern is what keeps a package's
    sibling binaries in one result -- ``pandoc-lua.1.gz`` and
    ``pandoc-server.1.gz`` alongside ``pandoc.1.gz`` -- while excluding
    unrelated files that share a section-like suffix by accident, such as
    mise's own numbered backup copies (``fzf.1.1``, ``fzf.1.12``, ...
    alongside ``fzf.1``, none of which fnmatch's fixed-width ``[1-9]`` class
    matches).

    Walks `_iter_install_root_manpage_files`, not `find_repo_manpage`'s own
    `_iter_repo_manpage_files`: an install root is a single package's
    extracted content, not an arbitrary checkout that can hold unrelated
    vendored trees, so it tolerates the one extra wrapper directory a
    release tarball's own top-level folder adds (mise's `gh` install keeps
    `gh_2.90.0_linux_amd64/share/man/man1/`, not `share/man/man1/` directly
    under root) -- a laxness `find_repo_manpage` deliberately does not carry.
    """
    exact_patterns, subcommand_patterns = _manpage_patterns(binary_name)
    patterns = exact_patterns + subcommand_patterns
    return sorted(
        path
        for path in _iter_install_root_manpage_files(root)
        if any(fnmatch.fnmatch(path.name, pattern) for pattern in patterns)
    )


def _manpage_patterns(binary_name: str) -> tuple[list[str], list[str]]:
    """Return (exact, subcommand) glob patterns across `_COMPRESSION_SUFFIXES`."""
    exact_patterns = [
        f"{binary_name}.[1-9]{suffix}" for suffix in _COMPRESSION_SUFFIXES
    ]
    subcommand_patterns = [
        f"{binary_name}-*.[1-9]{suffix}" for suffix in _COMPRESSION_SUFFIXES
    ]
    return exact_patterns, subcommand_patterns


def _iter_repo_manpage_files(repo_dir: Path) -> Iterator[Path]:
    """Yield files at a repository root and under its manpage trees."""
    if not repo_dir.is_dir():
        return
    yield from (item for item in repo_dir.iterdir() if item.is_file())
    for root, directories, files in os.walk(repo_dir):
        rel_dir = Path(root).relative_to(repo_dir)
        directories[:] = [d for d in directories if not d.startswith(".")]
        if rel_dir == Path("."):
            continue
        parts = tuple(part.lower() for part in rel_dir.parts)
        if not any(parts[: len(prefix)] == prefix for prefix in REPO_MANPAGE_DIRS):
            continue
        for filename in files:
            yield Path(root, filename)


# How many leading path segments below an install root `_iter_install_root_manpage_files`
# will skip over before requiring a `REPO_MANPAGE_DIRS` prefix to match -- one, the
# release-archive folder a tarball extracts into (`gh_2.90.0_linux_amd64/`,
# `pastel-v0.12.0-x86_64-unknown-linux-gnu/`), never unbounded: an install root holds
# one package's own content, not a checkout that could bury a coincidental `man/` dir
# arbitrarily deep in a vendored dependency.
_INSTALL_ROOT_WRAPPER_DEPTHS = (0, 1)


def _iter_install_root_manpage_files(root: Path) -> Iterator[Path]:
    """Yield files at an install root and under its manpage trees, tolerating
    one leading release-archive wrapper directory before them.
    """
    if not root.is_dir():
        return
    yield from (item for item in root.iterdir() if item.is_file())
    for path, directories, files in os.walk(root):
        rel_dir = Path(path).relative_to(root)
        directories[:] = [d for d in directories if not d.startswith(".")]
        if rel_dir == Path("."):
            continue
        parts = tuple(part.lower() for part in rel_dir.parts)
        matches = any(
            parts[depth : depth + len(prefix)] == prefix
            for prefix in REPO_MANPAGE_DIRS
            for depth in _INSTALL_ROOT_WRAPPER_DEPTHS
            if depth < len(parts)
        )
        if not matches:
            continue
        for filename in files:
            yield Path(path, filename)


def find_help_derived_manpages(
    manpath_bin: str,
    on_scan: Callable[[], None] | None = None,
    on_start: Callable[[int], None] | None = None,
) -> list[HelpDerivedManpage]:
    """List recognized help-derived pages in the active manpath."""
    pages = [
        page
        for page in _scan_manpath(manpath_bin, on_scan, on_start)
        if is_help2man_manpage(page.path)
    ]
    return _deduplicate_help_derived_manpages(pages)


def find_installed_manpages(
    manpath_bin: str,
    on_scan: Callable[[], None] | None = None,
    on_start: Callable[[int], None] | None = None,
) -> list[HelpDerivedManpage]:
    """List every identifiable page in the active manpath, generator or not."""
    return _deduplicate_help_derived_manpages(
        list(_scan_manpath(manpath_bin, on_scan, on_start))
    )


def _scan_manpath(
    manpath_bin: str,
    on_scan: Callable[[], None] | None,
    on_start: Callable[[int], None] | None,
) -> Iterator[HelpDerivedManpage]:
    """Identify every regular file in the active manpath as a candidate page."""
    result = subprocess.run([manpath_bin], capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise ManiacError("Could not determine the active manpath.")

    manpaths = [Path(entry) for entry in result.stdout.strip().split(":") if entry]
    paths = [path for manpath in manpaths for path in _iter_manpage_files(manpath)]
    if on_start is not None:
        on_start(len(paths))

    for path in paths:
        if on_scan is not None:
            on_scan()
        identity = _manpage_identity(path)
        if identity is None:
            continue
        name, section = identity
        yield HelpDerivedManpage(name=name, section=section, path=path)


def _deduplicate_help_derived_manpages(
    pages: list[HelpDerivedManpage],
) -> list[HelpDerivedManpage]:
    """Keep the shortest path for each name and section."""
    unique_pages: dict[tuple[str, str], HelpDerivedManpage] = {}
    for page in sorted(pages, key=lambda page: (len(page.path.parts), str(page.path))):
        unique_pages.setdefault((page.name, page.section), page)
    return sorted(
        unique_pages.values(),
        key=lambda page: (page.name, page.section, str(page.path)),
    )


def _iter_manpage_files(manpath: Path) -> Iterator[Path]:
    """Yield regular files from one local manpath directory."""
    if not manpath.is_dir():
        logger.debug("Skipping unavailable manpath directory", path=str(manpath))
        return

    for root, directories, files in os.walk(manpath):
        directories.sort()
        for filename in sorted(files):
            path = Path(root, filename)
            if path.is_file():
                yield path


def _manpage_identity(path: Path) -> tuple[str, str] | None:
    """Extract a page name and section from a standard manpage filename."""
    directory = path.parent.name
    if not directory.startswith("man") or len(directory) == 3:
        return None

    filename = path.name
    if path.suffix in {".bz2", ".gz", ".lzma", ".xz"}:
        filename = Path(filename).stem

    name, separator, section = filename.rpartition(".")
    if not separator or not name or not section.startswith(directory[3:]):
        return None
    return name, section


def _opener_for(path: Path) -> Callable[..., TextIO]:
    """Pick the file opener for a plain or standard-compressed manpage."""
    match path.suffix:
        case ".gz":
            return gzip.open
        case ".bz2":
            return bz2.open
        case ".xz" | ".lzma":
            return lzma.open
        case ".zst":
            return _zstd_open
        case _:
            return open


def _zstd_open(path: Path, mode: str, *, encoding: str, errors: str) -> TextIO:
    """Decompress a `.zst` manpage for text reading.

    Streams through `ZstdDecompressor`, matching `discovery.py`'s own use of
    the library, rather than the separate `zstandard.open` convenience
    wrapper.
    """
    if mode != "rt":
        raise ValueError(f"unsupported zstd open mode: {mode!r}")
    decompressor = zstandard.ZstdDecompressor()
    stream = decompressor.stream_reader(path.open("rb"))
    return io.TextIOWrapper(stream, encoding=encoding, errors=errors)


def _read_prefix(path: Path) -> str:
    """Read enough of a plain or standard-compressed manpage to identify it."""
    with _opener_for(path)(path, "rt", encoding="utf-8", errors="replace") as file:
        return file.read(_PREFIX_BYTES)
