"""Inspect installed manpages before treating them as authoritative."""

import bz2
import gzip
import lzma
import os
import subprocess
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from pathlib import Path

from ..exceptions import ManiacError
from ..logging import logger

HELP2MAN_MARKER = "it was generated by help2man"
_PREFIX_BYTES = 8_192


@dataclass(frozen=True, slots=True)
class ManpageStatus:
    """Whether an installed page exists and is generated by help2man."""

    exists: bool
    is_help2man: bool

    @property
    def is_usable(self) -> bool:
        """Whether the installed page is not generated by help2man."""
        return self.exists and not self.is_help2man


@dataclass(frozen=True, slots=True)
class HelpDerivedManpage:
    """A recognized help-derived manpage and its installed location."""

    name: str
    section: str
    path: Path


def inspect_manpage(man_bin: str, tool_name: str) -> ManpageStatus:
    """Inspect ``tool_name``'s installed page without rendering it."""
    result = subprocess.run(
        [man_bin, "-w", tool_name], capture_output=True, text=True, check=False
    )
    if result.returncode != 0 or not result.stdout.strip():
        return ManpageStatus(exists=False, is_help2man=False)

    paths = [Path(line) for line in result.stdout.splitlines() if line.strip()]
    return ManpageStatus(
        exists=True,
        is_help2man=bool(paths) and all(is_help2man_manpage(path) for path in paths),
    )


def is_help2man_manpage(path: Path) -> bool:
    """Whether a roff file carries help2man's generated-file marker."""
    try:
        prefix = _read_prefix(path)
    except (OSError, UnicodeError) as error:
        logger.debug("Unable to inspect manpage", path=str(path), error=str(error))
        return False
    return HELP2MAN_MARKER in prefix.lower()


def is_help2man_content(content: str) -> bool:
    """Whether roff content starts with help2man's generated-file marker."""
    return HELP2MAN_MARKER in content[:_PREFIX_BYTES].lower()


def find_help_derived_manpages(
    manpath_bin: str,
    on_scan: Callable[[], None] | None = None,
    on_start: Callable[[int], None] | None = None,
) -> list[HelpDerivedManpage]:
    """List recognized help-derived pages in the active manpath."""
    result = subprocess.run([manpath_bin], capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise ManiacError("Could not determine the active manpath.")

    manpaths = [Path(entry) for entry in result.stdout.strip().split(":") if entry]
    paths = [path for manpath in manpaths for path in _iter_manpage_files(manpath)]
    if on_start is not None:
        on_start(len(paths))

    pages: list[HelpDerivedManpage] = []
    for path in paths:
        if on_scan is not None:
            on_scan()
        identity = _manpage_identity(path)
        if identity is None or not is_help2man_manpage(path):
            continue
        name, section = identity
        pages.append(HelpDerivedManpage(name=name, section=section, path=path))
    return _deduplicate_help_derived_manpages(pages)


def _deduplicate_help_derived_manpages(
    pages: list[HelpDerivedManpage],
) -> list[HelpDerivedManpage]:
    """Keep the shortest path for each name and section."""
    unique_pages: dict[tuple[str, str], HelpDerivedManpage] = {}
    for page in sorted(pages, key=lambda page: (len(page.path.parts), str(page.path))):
        unique_pages.setdefault((page.name, page.section), page)
    return sorted(
        unique_pages.values(),
        key=lambda page: (page.name, page.section, str(page.path)),
    )


def _iter_manpage_files(manpath: Path) -> Iterator[Path]:
    """Yield regular files from one local manpath directory."""
    if not manpath.is_dir():
        logger.debug("Skipping unavailable manpath directory", path=str(manpath))
        return

    for root, directories, files in os.walk(manpath):
        directories.sort()
        for filename in sorted(files):
            path = Path(root, filename)
            if path.is_file():
                yield path


def _manpage_identity(path: Path) -> tuple[str, str] | None:
    """Extract a page name and section from a standard manpage filename."""
    directory = path.parent.name
    if not directory.startswith("man") or len(directory) == 3:
        return None

    filename = path.name
    if path.suffix in {".bz2", ".gz", ".lzma", ".xz"}:
        filename = Path(filename).stem

    name, separator, section = filename.rpartition(".")
    if not separator or not name or not section.startswith(directory[3:]):
        return None
    return name, section


def _read_prefix(path: Path) -> str:
    """Read enough of a plain or standard-compressed manpage to identify it."""
    opener: Callable[..., object]
    match path.suffix:
        case ".gz":
            opener = gzip.open
        case ".bz2":
            opener = bz2.open
        case ".xz" | ".lzma":
            opener = lzma.open
        case _:
            opener = open

    with opener(path, "rt", encoding="utf-8", errors="replace") as file:
        return file.read(_PREFIX_BYTES)
